import type { CategoryBatch } from "../types";

export const blogMediaBatch: CategoryBatch = {
  category: "Blog, Media & Publishing",
  specs: [
    {
      name: "The Signal — Tech Newsletter Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A sleek, dark-mode landing page for a tech and AI newsletter, built to convert readers into subscribers with a bold hero and a clear value proposition.",
      pageStyle: { backgroundColor: "#0b1220", color: "#e2e8f0", htmlTitle: "The Signal — Tech, Decoded Weekly" },
      sections: [
        {
          type: "hero",
          eyebrow: "READ BY 40,000+ BUILDERS",
          heading: "The Week's Most Important Tech News, Decoded",
          subheading: "No hype, no fluff — just the signal. Three minutes, every Thursday.",
          primaryCta: { text: "Subscribe Free", href: "#subscribe" },
          accentColor: "#22d3ee",
          textColor: "#e2e8f0",
          mutedColor: "#94a3b8",
        },
        {
          type: "richtext",
          heading: "Why Busy People Read The Signal",
          paragraphs: [
            "Every week we sift through hundreds of product launches, funding rounds, and research papers so you don't have to. What survives the cut is the stuff that actually matters for your work and your career.",
            "Written by two former engineers turned analysts, The Signal skips the press-release spin and tells you what a story really means — plainly, and without an agenda.",
          ],
          textColor: "#e2e8f0",
          mutedColor: "#94a3b8",
        },
        {
          type: "cta",
          heading: "Join 40,000 Builders Who Start Their Thursday With Us",
          subheading: "Free, forever. Unsubscribe in one click.",
          cta: { text: "Get The Signal", href: "#subscribe" },
          bg: "#22d3ee",
          textColor: "#0b1220",
          mutedColor: "#0f2b33",
        },
        {
          type: "footer",
          brand: "The Signal",
          menu: [{ label: "Archive" }, { label: "About" }, { label: "Sponsor Us" }],
          links: [{ provider: "x" }, { provider: "linkedin" }],
          copyright: "© The Signal. A weekly newsletter for people who build things.",
          bg: "#0b1220",
        },
      ],
    },
    {
      name: "Kindred Living — Digital Magazine Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A warm, editorial landing page for a lifestyle magazine that puts featured stories front and center and invites readers to keep exploring.",
      pageStyle: { backgroundColor: "#fff7ed", color: "#431407", htmlTitle: "Kindred Living Magazine" },
      sections: [
        {
          type: "hero",
          eyebrow: "ISSUE NO. 47",
          heading: "Slow Living, Well-Made Homes, and the Art of Staying Put",
          subheading: "Kindred Living is a digital magazine about building a life you don't need a vacation from.",
          primaryCta: { text: "Read the Latest Issue", href: "#stories" },
          accentColor: "#ea580c",
          textColor: "#431407",
          mutedColor: "#92400e",
        },
        {
          type: "grid",
          heading: "This Week's Stories",
          columns: 3,
          items: [
            { imageSeed: "kindred-kitchen-table", title: "The Case for a Smaller Kitchen", text: "Why less counter space might make you a better cook.", cta: { text: "Read Story", href: "#" } },
            { imageSeed: "kindred-sunday-ritual", title: "Building a Sunday Ritual That Sticks", text: "Three families on the small rituals that hold their week together.", cta: { text: "Read Story", href: "#" } },
            { imageSeed: "kindred-garden-notes", title: "Notes From a First-Year Garden", text: "What a novice gardener learned from a season of failure.", cta: { text: "Read Story", href: "#" } },
          ],
          accentColor: "#ea580c",
          textColor: "#431407",
          mutedColor: "#92400e",
        },
        {
          type: "cta",
          heading: "Get Kindred Living in Your Inbox",
          subheading: "One thoughtful email a week — no ads, no algorithm.",
          cta: { text: "Subscribe for Free", href: "#subscribe" },
          bg: "#ea580c",
          textColor: "#fff7ed",
        },
        {
          type: "footer",
          brand: "Kindred Living",
          menu: [{ label: "Stories" }, { label: "About" }, { label: "Contribute" }],
          links: [{ provider: "instagram" }, { provider: "pinterest" }],
          copyright: "© Kindred Living Magazine.",
          bg: "#431407",
        },
      ],
    },
    {
      name: "Wanderlark — Travel & Culture Magazine Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A rich, multi-section landing page for a travel and culture digital magazine — navigation, featured dispatches, readership stats, testimonials, and a full footer.",
      pageStyle: { backgroundColor: "#f5f2ea", color: "#1c1917", htmlTitle: "Wanderlark Magazine" },
      sections: [
        {
          type: "menubar",
          brand: "Wanderlark",
          links: [{ label: "Dispatches" }, { label: "Destinations" }, { label: "Culture" }, { label: "About" }],
          cta: { text: "Subscribe", href: "#subscribe" },
          bg: "#1c1917",
          textColor: "#f5f2ea",
          accentColor: "#b45309",
        },
        {
          type: "hero",
          eyebrow: "INDEPENDENT TRAVEL JOURNALISM",
          heading: "Stories From the Places the Guidebooks Skip",
          subheading: "Wanderlark sends writers to the overlooked corners of the map — and brings back the stories that stay with you.",
          primaryCta: { text: "Read Our Latest Dispatch", href: "#dispatches" },
          secondaryCta: { text: "Subscribe Free", href: "#subscribe" },
          imageSeed: "wanderlark-mountain-village",
          imageAlt: "A writer overlooking a mountain village at dusk",
          accentColor: "#b45309",
          textColor: "#1c1917",
          mutedColor: "#57534e",
        },
        {
          type: "grid",
          heading: "Latest Dispatches",
          columns: 3,
          items: [
            { imageSeed: "wanderlark-lisbon-trams", title: "Lisbon After the Tourists Go Home", text: "A week spent in the city's quiet hours.", cta: { text: "Read", href: "#" } },
            { imageSeed: "wanderlark-oaxaca-market", title: "The Last Market Vendors of Old Oaxaca", text: "Three generations, one dwindling trade.", cta: { text: "Read", href: "#" } },
            { imageSeed: "wanderlark-hokkaido-snow", title: "Snowbound in Rural Hokkaido", text: "Two weeks with a family that farms through winter.", cta: { text: "Read", href: "#" } },
          ],
          accentColor: "#b45309",
          textColor: "#1c1917",
          mutedColor: "#57534e",
        },
        {
          type: "stats",
          items: [
            { value: "180+", label: "Countries covered" },
            { value: "2.1M", label: "Monthly readers" },
            { value: "12", label: "Years in print & pixels" },
          ],
          accentColor: "#b45309",
          textColor: "#1c1917",
          mutedColor: "#57534e",
        },
        {
          type: "testimonials",
          heading: "What Readers Say",
          items: [
            { quote: "Wanderlark is the only travel writing I trust to tell me the truth about a place, good and bad.", name: "Naomi F.", role: "Subscriber since 2019" },
            { quote: "Their dispatches read like the best long-form journalism, not brochure copy.", name: "Devon R.", role: "Subscriber" },
          ],
          cardBg: "#efe9dc",
          textColor: "#1c1917",
          mutedColor: "#57534e",
        },
        {
          type: "footer",
          brand: "Wanderlark",
          menu: [{ label: "Dispatches" }, { label: "Masthead" }, { label: "Write for Us" }, { label: "Advertise" }],
          links: [{ provider: "instagram" }, { provider: "x" }, { provider: "youtube" }],
          copyright: "© Wanderlark Media. Independent travel journalism.",
          bg: "#1c1917",
        },
      ],
    },
    {
      name: "Offbeat Hours — Podcast & Blog Hub Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A vibrant hub page for a podcast-and-blog brand, combining episode highlights, listener stats, testimonials, and a behind-the-scenes photo gallery.",
      pageStyle: { backgroundColor: "#140f1f", color: "#f3f0fa", htmlTitle: "Offbeat Hours" },
      sections: [
        {
          type: "menubar",
          brand: "Offbeat Hours",
          links: [{ label: "Episodes" }, { label: "Blog" }, { label: "Guests" }, { label: "About" }],
          cta: { text: "Listen Now", href: "#episodes" },
          bg: "#140f1f",
          textColor: "#f3f0fa",
          accentColor: "#a855f7",
        },
        {
          type: "hero",
          eyebrow: "NEW EPISODE EVERY TUESDAY",
          heading: "Conversations for People Who Ask Too Many Questions",
          subheading: "Offbeat Hours is a podcast and blog about the weird, wonderful side projects, obsessions, and career pivots that never make it into a highlight reel.",
          primaryCta: { text: "Play Latest Episode", href: "#episodes" },
          secondaryCta: { text: "Read the Blog", href: "#blog" },
          accentColor: "#a855f7",
          textColor: "#f3f0fa",
          mutedColor: "#c4b5fd",
        },
        {
          type: "iconrow",
          heading: "Why Listeners Stick Around",
          items: [
            { iconName: "Mic", label: "Unscripted, hour-long conversations" },
            { iconName: "Headphones", label: "New episode every Tuesday" },
            { iconName: "BookOpen", label: "Companion essay for every episode" },
            { iconName: "Users", label: "120,000+ monthly listeners" },
          ],
          accentColor: "#a855f7",
          textColor: "#f3f0fa",
          mutedColor: "#c4b5fd",
        },
        {
          type: "grid",
          heading: "Recent Episodes & Essays",
          columns: 3,
          items: [
            { imageSeed: "offbeat-ep-84", title: "Ep. 84 — Quitting Medicine to Restore Typewriters", text: "A former ER doctor on trading scrubs for solder.", cta: { text: "Listen", href: "#" } },
            { imageSeed: "offbeat-ep-83", title: "Ep. 83 — The Woman Who Maps Abandoned Subway Lines", text: "Urban exploration as an act of memory.", cta: { text: "Listen", href: "#" } },
            { imageSeed: "offbeat-blog-1", title: "What We Learned From 100 Episodes", text: "A written companion piece to our anniversary episode.", cta: { text: "Read", href: "#" } },
          ],
          accentColor: "#a855f7",
          textColor: "#f3f0fa",
          mutedColor: "#c4b5fd",
        },
        {
          type: "testimonials",
          heading: "What Listeners Are Saying",
          items: [
            { quote: "This is the only podcast that's made me cry and laugh in the same episode.", name: "Priya M.", role: "Listener" },
            { quote: "The companion blog posts are honestly as good as the episodes.", name: "Sam T.", role: "Listener since Season 1" },
          ],
          cardBg: "#1f1830",
          textColor: "#f3f0fa",
          mutedColor: "#c4b5fd",
        },
        {
          type: "gallery",
          heading: "Behind the Mic",
          images: [
            { seed: "offbeat-studio-1", alt: "Hosts recording in the studio" },
            { seed: "offbeat-studio-2", alt: "Guest interview setup" },
            { seed: "offbeat-live-show", alt: "Live show at a local venue" },
          ],
          textColor: "#f3f0fa",
        },
        {
          type: "footer",
          brand: "Offbeat Hours",
          menu: [{ label: "All Episodes" }, { label: "Blog" }, { label: "Merch" }, { label: "Sponsor" }],
          links: [{ provider: "instagram" }, { provider: "youtube" }, { provider: "spotify" }],
          copyright: "© Offbeat Hours Media.",
          bg: "#140f1f",
        },
      ],
    },
    {
      name: "New Issue Notification Email — The Signal",
      kind: "EMAIL",
      tier: "quick",
      description: "A minimal, fast-to-scan email alerting subscribers that a fresh newsletter issue just went out, with a quick summary and a read link.",
      pageStyle: { backgroundColor: "#ffffff", color: "#0f172a", htmlTitle: "This Week's Signal Just Landed" },
      sections: [
        {
          type: "hero",
          eyebrow: "ISSUE #212",
          heading: "This Week: The Chip Shortage That Wasn't, and 3 AI Tools Worth Your Time",
          subheading: "Your Thursday issue of The Signal just landed.",
          primaryCta: { text: "Read the Full Issue", href: "#read" },
          accentColor: "#0891b2",
          mutedColor: "#64748b",
        },
        {
          type: "richtext",
          heading: "In This Issue",
          paragraphs: [
            "Why the predicted chip shortage fizzled out — and what that tells us about the rest of the year. Plus, three AI tools our readers have actually kept using past the novelty phase, and a quick take on last week's biggest funding round.",
            "As always, replies go straight to our inbox — we read every one.",
          ],
          mutedColor: "#64748b",
        },
        {
          type: "cta",
          heading: "Read the Full Breakdown",
          subheading: "Three minutes, no fluff.",
          cta: { text: "Open This Week's Issue", href: "#read" },
          bg: "#0891b2",
          textColor: "#ffffff",
        },
        {
          type: "footer",
          brand: "The Signal",
          copyright: "© The Signal. You're subscribed because you signed up at thesignal.news.",
          bg: "#0f172a",
        },
      ],
    },
    {
      name: "Subscriber Welcome Email — Kindred Living",
      kind: "EMAIL",
      tier: "quick",
      description: "A warm welcome email for new magazine subscribers that sets expectations and points them to a few reader-favorite stories to start with.",
      pageStyle: { backgroundColor: "#fff7ed", color: "#431407", htmlTitle: "Welcome to Kindred Living" },
      sections: [
        {
          type: "hero",
          eyebrow: "WELCOME",
          heading: "Glad You're Here",
          subheading: "You're now part of a community of 60,000 readers building slower, more intentional lives.",
          accentColor: "#ea580c",
          mutedColor: "#92400e",
        },
        {
          type: "richtext",
          heading: "What to Expect",
          paragraphs: [
            "Every Sunday morning, we'll send you one issue — a mix of essays, home tours, and small-scale living guides, written by people actually living the ideas they write about.",
            "No sponsored fluff, no clickbait. Just the good stuff, once a week.",
          ],
          mutedColor: "#92400e",
        },
        {
          type: "grid",
          heading: "Start With These Reader Favorites",
          columns: 3,
          items: [
            { imageSeed: "kindred-fav-1", title: "The One-Bag Household", text: "A family of four on downsizing to a single carry-on each.", cta: { text: "Read", href: "#" } },
            { imageSeed: "kindred-fav-2", title: "Cooking for One, Well", text: "Why solo dinners deserve real recipes too.", cta: { text: "Read", href: "#" } },
            { imageSeed: "kindred-fav-3", title: "The Porch Renaissance", text: "How a forgotten space became the heart of the home.", cta: { text: "Read", href: "#" } },
          ],
          accentColor: "#ea580c",
        },
        {
          type: "footer",
          brand: "Kindred Living",
          copyright: "© Kindred Living Magazine. You're receiving this because you subscribed at kindredliving.co.",
          bg: "#431407",
        },
      ],
    },
    {
      name: "Weekly Digest Email — Wanderlark Roundup",
      kind: "EMAIL",
      tier: "premium",
      description: "A content-rich weekly roundup email for a travel and culture magazine, bundling the week's top dispatches with an editor's note and reader testimonials.",
      pageStyle: { backgroundColor: "#f5f2ea", color: "#1c1917", htmlTitle: "Your Wanderlark Weekly Roundup" },
      sections: [
        {
          type: "hero",
          eyebrow: "WEEKLY ROUNDUP",
          heading: "This Week on Wanderlark: Lisbon, Oaxaca, and a Farewell to Print Maps",
          subheading: "Five dispatches, one editor's note, and the photo of the week.",
          primaryCta: { text: "Browse This Week's Stories", href: "#stories" },
          accentColor: "#b45309",
          mutedColor: "#57534e",
        },
        {
          type: "richtext",
          heading: "A Note From the Editor",
          paragraphs: [
            "This week our writers covered three continents and filed dispatches on everything from disappearing market trades to a farewell letter to paper maps. My personal favorite is the Hokkaido piece — it's a slow read, but worth the twenty minutes.",
            "As always, thank you for reading and for telling a friend. We grow almost entirely by word of mouth.",
          ],
          mutedColor: "#57534e",
        },
        {
          type: "grid",
          heading: "This Week's Dispatches",
          columns: 3,
          items: [
            { imageSeed: "wanderlark-digest-1", title: "Lisbon After the Tourists Go Home", text: "A week spent in the city's quiet hours.", cta: { text: "Read", href: "#" } },
            { imageSeed: "wanderlark-digest-2", title: "The Last Market Vendors of Old Oaxaca", text: "Three generations, one dwindling trade.", cta: { text: "Read", href: "#" } },
            { imageSeed: "wanderlark-digest-3", title: "A Farewell to Paper Maps", text: "On the quiet death of a travel ritual.", cta: { text: "Read", href: "#" } },
          ],
          accentColor: "#b45309",
          mutedColor: "#57534e",
        },
        {
          type: "testimonials",
          heading: "From Our Readers",
          items: [{ quote: "I look forward to this email more than almost anything else in my inbox.", name: "Claire O.", role: "Subscriber" }],
          cardBg: "#efe9dc",
          textColor: "#1c1917",
          mutedColor: "#57534e",
        },
        {
          type: "footer",
          brand: "Wanderlark",
          copyright: "© Wanderlark Media. Manage your subscription preferences anytime.",
          bg: "#1c1917",
        },
      ],
    },
    {
      name: "Newsletter Signup Page — The Signal",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A short, high-converting opt-in page for a tech newsletter, pairing a sharp value proposition with a single-field signup form.",
      pageStyle: { backgroundColor: "#0b1220", color: "#e2e8f0", htmlTitle: "Subscribe to The Signal" },
      sections: [
        {
          type: "hero",
          eyebrow: "FREE WEEKLY NEWSLETTER",
          heading: "Get The Signal Every Thursday",
          subheading: "The tech news that actually matters, explained in three minutes. Joined by 40,000 builders, founders, and engineers.",
          accentColor: "#22d3ee",
          mutedColor: "#94a3b8",
        },
        {
          type: "form",
          heading: "Subscribe for Free",
          subheading: "One email a week. Unsubscribe anytime.",
          fields: [{ kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true }],
          submitLabel: "Send Me The Signal",
          accentColor: "#22d3ee",
        },
        {
          type: "footer",
          brand: "The Signal",
          copyright: "© The Signal.",
          bg: "#0b1220",
        },
      ],
    },
    {
      name: "Free Guide Download Page — Kindred Living",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A cozy opt-in landing page offering a free seasonal living guide in exchange for an email address, with a light benefits list for reassurance.",
      pageStyle: { backgroundColor: "#fff7ed", color: "#431407", htmlTitle: "Get the Free Seasonal Reset Guide" },
      sections: [
        {
          type: "hero",
          eyebrow: "FREE DOWNLOAD",
          heading: "The Seasonal Reset Guide",
          subheading: "A 24-page guide to decluttering, rearranging, and slowing down as the seasons change — free for Kindred Living readers.",
          imageSeed: "kindred-guide-cover",
          imageAlt: "Seasonal Reset Guide cover on a wooden table",
          accentColor: "#ea580c",
          mutedColor: "#92400e",
        },
        {
          type: "form",
          heading: "Send Me the Guide",
          fields: [
            { kind: "text", label: "First Name", name: "firstName", placeholder: "Jane", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
          ],
          submitLabel: "Get My Free Guide",
          accentColor: "#ea580c",
        },
        {
          type: "iconrow",
          items: [
            { iconName: "BookOpen", label: "24-page printable PDF" },
            { iconName: "Leaf", label: "Season-by-season checklists" },
            { iconName: "Mail", label: "Delivered straight to your inbox" },
          ],
          accentColor: "#ea580c",
        },
        {
          type: "footer",
          brand: "Kindred Living",
          copyright: "© Kindred Living Magazine.",
          bg: "#431407",
        },
      ],
    },
    {
      name: "Become a Contributor Signup Page — Offbeat Hours",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A call-for-writers opt-in page inviting readers to pitch essays and story ideas to a podcast-and-blog brand, with a short signup form and pipeline stats.",
      pageStyle: { backgroundColor: "#140f1f", color: "#f3f0fa", htmlTitle: "Write for Offbeat Hours" },
      sections: [
        {
          type: "hero",
          eyebrow: "CALL FOR CONTRIBUTORS",
          heading: "Got a Story Only You Could Tell?",
          subheading: "We're always looking for new voices for the Offbeat Hours blog — unusual careers, strange hobbies, quiet obsessions. Tell us about yours.",
          accentColor: "#a855f7",
          mutedColor: "#c4b5fd",
        },
        {
          type: "form",
          heading: "Pitch Us Your Story",
          fields: [
            { kind: "text", label: "Name", name: "name", placeholder: "Your name", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
            { kind: "textarea", label: "Your Story Idea", name: "pitch", placeholder: "In a few sentences, what's the story?", required: true },
          ],
          submitLabel: "Submit My Pitch",
          accentColor: "#a855f7",
        },
        {
          type: "stats",
          items: [
            { value: "400+", label: "Pitches read every month" },
            { value: "1 in 12", label: "Pitches we publish" },
            { value: "48 hrs", label: "Average response time" },
          ],
          accentColor: "#a855f7",
        },
        {
          type: "footer",
          brand: "Offbeat Hours",
          copyright: "© Offbeat Hours Media.",
          bg: "#140f1f",
        },
      ],
    },
  ],
};
