import type { CategoryBatch } from "../types";

export const ecommerceBatch: CategoryBatch = {
  category: "Ecommerce & Retail",
  specs: [
    {
      name: "Lumen Footwear — Product Showcase Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A clean, image-led landing page for showcasing a footwear or apparel collection with a hero, product grid, and CTA.",
      pageStyle: { backgroundColor: "#ffffff", color: "#111827", htmlTitle: "Lumen Footwear" },
      sections: [
        {
          type: "hero",
          eyebrow: "NEW COLLECTION",
          heading: "Step Into Comfort, Walk With Confidence",
          subheading: "Handcrafted sneakers built for everyday movement — lightweight, durable, and designed to last.",
          primaryCta: { text: "Shop the Collection", href: "#shop" },
          imageSeed: "lumen-footwear-hero",
          imageAlt: "Lumen sneaker on display",
          textColor: "#111827",
          mutedColor: "#6b7280",
          accentColor: "#111827",
        },
        {
          type: "grid",
          heading: "Bestsellers This Season",
          columns: 3,
          items: [
            { imageSeed: "lumen-urban-runner", title: "Urban Runner", text: "Lightweight sneakers for daily adventures", price: "$89", cta: { text: "Add to Cart", href: "#" } },
            { imageSeed: "lumen-classic-court", title: "Classic Court", text: "Timeless style with modern comfort", price: "$79", cta: { text: "Add to Cart", href: "#" } },
            { imageSeed: "lumen-street-flex", title: "Street Flex", text: "Flexible performance footwear", price: "$99", cta: { text: "Add to Cart", href: "#" } },
          ],
          accentColor: "#111827",
          textColor: "#111827",
          mutedColor: "#6b7280",
        },
        {
          type: "cta",
          heading: "Free Shipping on Orders Over $75",
          subheading: "Plus free returns within 30 days — shop risk-free.",
          cta: { text: "Shop Now", href: "#shop" },
          bg: "#111827",
        },
        {
          type: "footer",
          brand: "Lumen Footwear",
          menu: [{ label: "Shop" }, { label: "About" }, { label: "Support" }],
          links: [{ provider: "instagram" }, { provider: "tiktok" }, { provider: "facebook" }],
          copyright: "© Lumen Footwear. All rights reserved.",
          bg: "#0f172a",
        },
      ],
    },
    {
      name: "Nordic Home Co. — Minimalist Product Launch Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A calm, minimalist single-product launch page with social proof stats and a strong call to action.",
      pageStyle: { backgroundColor: "#f8fafc", color: "#0f172a", htmlTitle: "Nordic Home Co." },
      sections: [
        {
          type: "hero",
          eyebrow: "LAUNCHING TODAY",
          heading: "The Ceramic Pour-Over Set, Reimagined",
          subheading: "Slow-crafted stoneware for a quieter morning ritual. Limited first run of 500 sets.",
          primaryCta: { text: "Reserve Yours — $64", href: "#buy" },
          accentColor: "#059669",
          mutedColor: "#64748b",
        },
        {
          type: "stats",
          items: [
            { value: "12,000+", label: "Sets sold worldwide" },
            { value: "4.9/5", label: "Average rating" },
            { value: "500", label: "First-run units left" },
          ],
          accentColor: "#059669",
        },
        {
          type: "cta",
          heading: "Only 500 First-Run Sets Available",
          subheading: "Once they're gone, the next batch ships in 8 weeks.",
          cta: { text: "Reserve Yours Now", href: "#buy" },
          bg: "#059669",
        },
        {
          type: "footer",
          brand: "Nordic Home Co.",
          links: [{ provider: "instagram" }, { provider: "pinterest" }],
          copyright: "© Nordic Home Co. Crafted in small batches.",
          bg: "#0f172a",
        },
      ],
    },
    {
      name: "Velora Marketplace — Full Storefront Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A rich, multi-section storefront landing page with navigation, bestsellers, trust badges, testimonials, and a full footer — built for a full product catalog.",
      pageStyle: { backgroundColor: "#0b0f19", color: "#f1f5f9", htmlTitle: "Velora Marketplace" },
      sections: [
        {
          type: "menubar",
          brand: "Velora",
          links: [{ label: "New In" }, { label: "Categories" }, { label: "Sale" }, { label: "Account" }],
          cta: { text: "Shop Now", href: "#shop" },
          bg: "#0b0f19",
          textColor: "#f1f5f9",
          accentColor: "#dc2626",
        },
        {
          type: "hero",
          eyebrow: "MARKETPLACE OF THE YEAR",
          heading: "Everything You Love, All in One Store",
          subheading: "From home goods to electronics — curated brands, unbeatable prices, delivered fast.",
          primaryCta: { text: "Start Shopping", href: "#shop" },
          secondaryCta: { text: "View Deals", href: "#deals" },
          imageSeed: "velora-storefront-hero",
          imageAlt: "Velora marketplace product spread",
          textColor: "#f1f5f9",
          mutedColor: "#94a3b8",
          accentColor: "#dc2626",
        },
        {
          type: "grid",
          heading: "Trending Right Now",
          columns: 4,
          items: [
            { imageSeed: "velora-item-1", title: "Wireless Earbuds Pro", price: "$59", cta: { text: "View", href: "#" } },
            { imageSeed: "velora-item-2", title: "Ceramic Cookware Set", price: "$129", cta: { text: "View", href: "#" } },
            { imageSeed: "velora-item-3", title: "Weighted Travel Backpack", price: "$74", cta: { text: "View", href: "#" } },
            { imageSeed: "velora-item-4", title: "Smart Desk Lamp", price: "$39", cta: { text: "View", href: "#" } },
          ],
          accentColor: "#dc2626",
          textColor: "#f1f5f9",
          mutedColor: "#94a3b8",
          bg: "#0f172a",
        },
        {
          type: "testimonials",
          heading: "Loved By Millions of Shoppers",
          items: [
            { quote: "Fast shipping and the quality always matches the photos. My go-to store.", name: "Priya N.", role: "Verified Buyer" },
            { quote: "Customer support resolved my issue in minutes. Genuinely impressed.", name: "Marcus D.", role: "Verified Buyer" },
            { quote: "The best marketplace for finding niche brands I can't get anywhere else.", name: "Elena R.", role: "Verified Buyer" },
          ],
          cardBg: "#0f172a",
          textColor: "#f1f5f9",
          mutedColor: "#94a3b8",
        },
        {
          type: "iconrow",
          heading: "Why Shop With Velora",
          items: [
            { iconName: "Truck", label: "Free 2-Day Shipping" },
            { iconName: "ShieldCheck", label: "Secure Checkout" },
            { iconName: "RotateCcw", label: "Easy 30-Day Returns" },
            { iconName: "Headphones", label: "24/7 Support" },
          ],
          accentColor: "#dc2626",
          textColor: "#f1f5f9",
          mutedColor: "#94a3b8",
        },
        {
          type: "footer",
          brand: "Velora Marketplace",
          menu: [{ label: "Help Center" }, { label: "Track Order" }, { label: "Returns" }, { label: "Careers" }],
          links: [{ provider: "instagram" }, { provider: "facebook" }, { provider: "x" }, { provider: "youtube" }],
          copyright: "© Velora Marketplace, Inc. All rights reserved.",
          bg: "#0b0f19",
        },
      ],
    },
    {
      name: "Solstice Outdoor — Flash Sale Countdown Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A high-urgency flash-sale landing page with a live countdown timer, discounted product grid, and navigation — built to convert during time-boxed promotions.",
      pageStyle: { backgroundColor: "#1c1917", color: "#fef3c7", htmlTitle: "Solstice Outdoor — Flash Sale" },
      sections: [
        {
          type: "menubar",
          brand: "Solstice Outdoor",
          links: [{ label: "Gear" }, { label: "Apparel" }, { label: "Sale" }],
          cta: { text: "Shop Sale", href: "#sale" },
          bg: "#1c1917",
          textColor: "#fef3c7",
          accentColor: "#f97316",
        },
        {
          type: "hero",
          eyebrow: "48 HOURS ONLY",
          heading: "Up to 60% Off Camping & Hiking Gear",
          subheading: "Our biggest outdoor sale of the year — while stock lasts.",
          primaryCta: { text: "Shop the Sale", href: "#sale" },
          textColor: "#fef3c7",
          mutedColor: "#fcd9a4",
          accentColor: "#f97316",
        },
        {
          type: "countdown",
          heading: "Sale Ends In",
          subheading: "Prices return to normal once the timer hits zero.",
          targetDate: "2026-12-31T23:59:59",
          bg: "#292524",
          textColor: "#fef3c7",
          mutedColor: "#fcd9a4",
        },
        {
          type: "grid",
          heading: "Top Deals",
          columns: 3,
          items: [
            { imageSeed: "solstice-tent", title: "4-Season Tent", text: "Was $349", price: "Now $189", cta: { text: "Shop Now", href: "#" } },
            { imageSeed: "solstice-pack", title: "60L Trail Backpack", text: "Was $220", price: "Now $99", cta: { text: "Shop Now", href: "#" } },
            { imageSeed: "solstice-boots", title: "Waterproof Hiking Boots", text: "Was $180", price: "Now $79", cta: { text: "Shop Now", href: "#" } },
          ],
          accentColor: "#f97316",
          textColor: "#fef3c7",
          mutedColor: "#fcd9a4",
        },
        {
          type: "cta",
          heading: "Don't Miss Out",
          subheading: "Once this sale ends, these prices are gone for good.",
          cta: { text: "Shop the Flash Sale", href: "#sale" },
          bg: "#f97316",
          textColor: "#1c1917",
          mutedColor: "#3f2c14",
        },
        {
          type: "footer",
          brand: "Solstice Outdoor",
          links: [{ provider: "instagram" }, { provider: "youtube" }],
          copyright: "© Solstice Outdoor. Gear up. Get out.",
          bg: "#1c1917",
        },
      ],
    },
    {
      name: "Order Confirmation Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A clean order-confirmation email with an itemized order summary table and a track-order call to action.",
      pageStyle: { backgroundColor: "#ffffff", color: "#0f172a", htmlTitle: "Your Order is Confirmed" },
      sections: [
        {
          type: "hero",
          heading: "Thanks for Your Order, Alex!",
          subheading: "Order #48213 has been confirmed and is being prepared for shipment.",
          accentColor: "#2563eb",
          mutedColor: "#64748b",
        },
        {
          type: "table",
          heading: "Order Summary",
          headers: ["Item", "Qty", "Price"],
          rows: [
            ["Urban Runner Sneakers — Size 9", "1", "$89.00"],
            ["Classic Court Sneakers — Size 9", "1", "$79.00"],
            ["Shipping", "—", "$0.00"],
          ],
        },
        {
          type: "cta",
          heading: "Track Your Shipment",
          subheading: "We'll email you again once your order ships.",
          cta: { text: "Track My Order", href: "#track" },
          bg: "#2563eb",
        },
        {
          type: "footer",
          brand: "Lumen Footwear",
          copyright: "© Lumen Footwear. Questions? Reply to this email.",
          bg: "#0f172a",
        },
      ],
    },
    {
      name: "Welcome Email with Discount Code",
      kind: "EMAIL",
      tier: "quick",
      description: "A warm welcome email that delivers a first-order discount code alongside a handful of featured products.",
      pageStyle: { backgroundColor: "#faf5ff", color: "#0f172a", htmlTitle: "Welcome to Velora" },
      sections: [
        {
          type: "hero",
          eyebrow: "WELCOME",
          heading: "You're In! Here's 15% Off Your First Order",
          subheading: "Use code WELCOME15 at checkout — valid for the next 7 days.",
          primaryCta: { text: "Shop Now", href: "#shop" },
          accentColor: "#9333ea",
          mutedColor: "#6b7280",
        },
        {
          type: "richtext",
          heading: "A Little About Us",
          paragraphs: ["Velora curates the best independent brands across home, fashion, and tech so you don't have to hunt for them yourself. Every product is vetted for quality before it ever reaches our shelves."],
          mutedColor: "#4b5563",
        },
        {
          type: "grid",
          heading: "Popular Picks to Start With",
          columns: 3,
          items: [
            { imageSeed: "velora-welcome-1", title: "Ceramic Cookware Set", price: "$129" },
            { imageSeed: "velora-welcome-2", title: "Weighted Travel Backpack", price: "$74" },
            { imageSeed: "velora-welcome-3", title: "Smart Desk Lamp", price: "$39" },
          ],
          accentColor: "#9333ea",
        },
        {
          type: "footer",
          brand: "Velora Marketplace",
          copyright: "© Velora Marketplace. You're receiving this because you signed up at velora.com.",
          bg: "#1e1b2e",
        },
      ],
    },
    {
      name: "Abandoned Cart Recovery Email",
      kind: "EMAIL",
      tier: "premium",
      description: "A conversion-focused cart-recovery email combining the abandoned items, an incentive CTA, related new arrivals, and social proof — built for automated recovery flows.",
      pageStyle: { backgroundColor: "#fff1f5", color: "#111827", htmlTitle: "You Left Something Behind" },
      sections: [
        {
          type: "hero",
          eyebrow: "STILL THINKING IT OVER?",
          heading: "Your Cart Is Waiting For You",
          subheading: "The items below are still reserved — but not for long.",
          accentColor: "#db2777",
          mutedColor: "#6b7280",
        },
        {
          type: "grid",
          heading: "In Your Cart",
          columns: 2,
          items: [
            { imageSeed: "cart-item-1", title: "Ceramic Pour-Over Set", price: "$64", cta: { text: "Complete Purchase", href: "#checkout" } },
            { imageSeed: "cart-item-2", title: "Weighted Travel Backpack", price: "$74", cta: { text: "Complete Purchase", href: "#checkout" } },
          ],
          accentColor: "#db2777",
        },
        {
          type: "cta",
          heading: "Complete Your Order — Get 10% Off",
          subheading: "Use code COMEBACK10 within the next 24 hours.",
          cta: { text: "Finish Checkout", href: "#checkout" },
          bg: "#db2777",
        },
        {
          type: "grid",
          heading: "You Might Also Like",
          columns: 3,
          items: [
            { imageSeed: "new-arrival-1", title: "Smart Desk Lamp", price: "$39" },
            { imageSeed: "new-arrival-2", title: "Wireless Earbuds Pro", price: "$59" },
            { imageSeed: "new-arrival-3", title: "4-Season Tent", price: "$189" },
          ],
        },
        {
          type: "testimonials",
          items: [{ quote: "I almost forgot my cart — glad they reminded me! Checkout took 30 seconds.", name: "Jordan K.", role: "Verified Buyer" }],
          cardBg: "#ffffff",
        },
        {
          type: "footer",
          brand: "Velora Marketplace",
          copyright: "© Velora Marketplace. Manage your email preferences anytime.",
          bg: "#1e1b2e",
        },
      ],
    },
    {
      name: "VIP Early Access Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A short, focused opt-in page collecting emails for early access to new product drops before public release.",
      pageStyle: { backgroundColor: "#ecfeff", color: "#0f172a", htmlTitle: "VIP Early Access" },
      sections: [
        {
          type: "hero",
          eyebrow: "VIP LIST",
          heading: "Get Early Access to Every New Drop",
          subheading: "Join the VIP list and shop new collections 24 hours before everyone else.",
          accentColor: "#0891b2",
          mutedColor: "#475569",
        },
        {
          type: "form",
          heading: "Join the VIP List",
          subheading: "One email a week, max. Unsubscribe anytime.",
          fields: [{ kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true }],
          submitLabel: "Get Early Access",
          accentColor: "#0891b2",
        },
        {
          type: "footer",
          brand: "Lumen Footwear",
          copyright: "© Lumen Footwear.",
          bg: "#0f172a",
        },
      ],
    },
    {
      name: "First Order Discount Opt-In Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A trust-building opt-in landing page offering a first-order discount code in exchange for an email signup.",
      pageStyle: { backgroundColor: "#f0fdf4", color: "#14532d", htmlTitle: "Get 10% Off Your First Order" },
      sections: [
        {
          type: "hero",
          heading: "Get 10% Off Your First Order",
          subheading: "Sign up below and we'll send your discount code instantly.",
          accentColor: "#16a34a",
          mutedColor: "#4b5563",
        },
        {
          type: "form",
          heading: "Where Should We Send Your Code?",
          fields: [
            { kind: "text", label: "First Name", name: "firstName", placeholder: "Jane", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
          ],
          submitLabel: "Send My Discount Code",
          accentColor: "#16a34a",
        },
        {
          type: "iconrow",
          items: [
            { iconName: "ShieldCheck", label: "No spam, ever" },
            { iconName: "Truck", label: "Free shipping over $75" },
            { iconName: "RotateCcw", label: "30-day returns" },
          ],
          accentColor: "#16a34a",
        },
        {
          type: "footer",
          brand: "Velora Marketplace",
          copyright: "© Velora Marketplace.",
          bg: "#0f2417",
        },
      ],
    },
    {
      name: "Restock Notification Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A minimal opt-in page for a sold-out product, collecting emails to notify shoppers the moment it's back in stock.",
      pageStyle: { backgroundColor: "#eef2ff", color: "#1e1b4b", htmlTitle: "Notify Me When Back in Stock" },
      sections: [
        {
          type: "hero",
          eyebrow: "SOLD OUT",
          heading: "The Ceramic Pour-Over Set Sold Out Fast",
          subheading: "Leave your email and we'll notify you the second it's back in stock.",
          imageSeed: "restock-pour-over",
          imageAlt: "Ceramic pour-over set",
          accentColor: "#4338ca",
          mutedColor: "#4b5563",
        },
        {
          type: "form",
          heading: "Notify Me",
          fields: [{ kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true }],
          submitLabel: "Notify Me When Available",
          accentColor: "#4338ca",
        },
        {
          type: "footer",
          brand: "Nordic Home Co.",
          copyright: "© Nordic Home Co.",
          bg: "#1e1b4b",
        },
      ],
    },
  ],
};
