import type { CategoryBatch } from "../types";

export const educationBatch: CategoryBatch = {
  category: "Education & Online Courses",
  specs: [
    {
      name: "CodeForge Academy — Full-Stack Bootcamp Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A fast, conversion-focused landing page for a coding bootcamp, pairing a bold hero with a curriculum breakdown and a clear enroll-now call to action.",
      pageStyle: { backgroundColor: "#0b1120", color: "#e2e8f0", htmlTitle: "CodeForge Academy" },
      sections: [
        {
          type: "hero",
          eyebrow: "12-WEEK IMMERSIVE BOOTCAMP",
          heading: "Become a Software Engineer in 12 Weeks",
          subheading: "Learn full-stack development from working engineers — no CS degree required, all you need is drive.",
          primaryCta: { text: "Apply Now", href: "#apply" },
          secondaryCta: { text: "See the Curriculum", href: "#curriculum" },
          imageSeed: "codeforge-hero-classroom",
          imageAlt: "Students collaborating on laptops in the CodeForge Academy classroom",
          textColor: "#e2e8f0",
          mutedColor: "#94a3b8",
          accentColor: "#22d3ee",
        },
        {
          type: "grid",
          heading: "What You'll Build & Learn",
          columns: 3,
          items: [
            { iconName: "BookOpen", title: "Weeks 1–4: Web Foundations", text: "HTML, CSS, JavaScript, and Git fundamentals, plus your first deployed project." },
            { iconName: "Zap", title: "Weeks 5–8: Full-Stack Development", text: "React, Node.js, REST APIs, and databases — you'll ship a full-stack app solo." },
            { iconName: "Briefcase", title: "Weeks 9–12: Capstone & Career Prep", text: "A team capstone project, mock interviews, and resume workshops with hiring partners." },
          ],
          accentColor: "#22d3ee",
          textColor: "#e2e8f0",
          mutedColor: "#94a3b8",
        },
        {
          type: "cta",
          heading: "Applications for the Fall Cohort Close Soon",
          subheading: "Seats are limited to 24 students per cohort to keep class sizes small.",
          cta: { text: "Enroll Now", href: "#apply" },
          bg: "#22d3ee",
          textColor: "#0b1120",
          mutedColor: "#0f2f38",
        },
        {
          type: "footer",
          brand: "CodeForge Academy",
          menu: [{ label: "Curriculum" }, { label: "Admissions" }, { label: "Outcomes" }],
          links: [{ provider: "linkedin" }, { provider: "instagram" }, { provider: "youtube" }],
          copyright: "© CodeForge Academy. All rights reserved.",
          bg: "#0a0e17",
        },
      ],
    },
    {
      name: "Lingora — Language Learning App Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A bright, friendly landing page for a language-learning app, highlighting bite-sized daily lessons and a strong free-trial call to action.",
      pageStyle: { backgroundColor: "#f0fdfa", color: "#134e4a", htmlTitle: "Lingora" },
      sections: [
        {
          type: "hero",
          eyebrow: "SPEAK FROM DAY ONE",
          heading: "Learn a New Language in Just 10 Minutes a Day",
          subheading: "Lingora turns your commute, coffee break, or bedtime scroll into real fluency — one bite-sized lesson at a time.",
          primaryCta: { text: "Start Learning Free", href: "#start" },
          imageSeed: "lingora-app-hero",
          imageAlt: "Lingora mobile app lesson screen",
          textColor: "#134e4a",
          mutedColor: "#5f8a86",
          accentColor: "#0d9488",
        },
        {
          type: "grid",
          heading: "Lessons Built Around How You Actually Learn",
          columns: 3,
          items: [
            { iconName: "Mic", title: "Speak From Lesson One", text: "Voice-recognition drills get your pronunciation right from the start." },
            { iconName: "Target", title: "Bite-Sized & Personalized", text: "Adaptive lessons focus on the words and grammar you actually need." },
            { iconName: "Users", title: "Practice With Real People", text: "Join live conversation clubs with learners at your exact level." },
          ],
          accentColor: "#0d9488",
          textColor: "#134e4a",
          mutedColor: "#5f8a86",
        },
        {
          type: "stats",
          items: [
            { value: "3M+", label: "Active learners" },
            { value: "40+", label: "Languages offered" },
            { value: "92%", label: "Say they'd recommend Lingora" },
          ],
          accentColor: "#0d9488",
          textColor: "#134e4a",
          mutedColor: "#5f8a86",
        },
        {
          type: "cta",
          heading: "Your First Lesson Is Free — No Card Required",
          subheading: "Join 3 million learners already speaking with confidence.",
          cta: { text: "Try Lingora Free", href: "#start" },
          bg: "#0d9488",
          textColor: "#f0fdfa",
          mutedColor: "#ccfbf1",
        },
        {
          type: "footer",
          brand: "Lingora",
          menu: [{ label: "Languages" }, { label: "Pricing" }, { label: "Blog" }],
          links: [{ provider: "instagram" }, { provider: "tiktok" }, { provider: "youtube" }],
          copyright: "© Lingora. All rights reserved.",
          bg: "#0f2e2c",
        },
      ],
    },
    {
      name: "CodeForge Academy — Full-Stack Bootcamp Premium Enrollment Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A comprehensive bootcamp enrollment page with navigation, an intro video, outcomes data, curriculum breakdown, graduate testimonials, and cohort pricing — built to convert serious applicants.",
      pageStyle: { backgroundColor: "#0a0e17", color: "#e2e8f0", htmlTitle: "CodeForge Academy — Enroll" },
      sections: [
        {
          type: "menubar",
          brand: "CodeForge Academy",
          links: [{ label: "Curriculum" }, { label: "Outcomes" }, { label: "Tuition" }, { label: "Apply" }],
          cta: { text: "Apply Now", href: "#apply" },
          bg: "#0a0e17",
          textColor: "#e2e8f0",
          accentColor: "#22d3ee",
        },
        {
          type: "hero",
          eyebrow: "12-WEEK IMMERSIVE BOOTCAMP",
          heading: "Go From Zero to Hired Software Engineer",
          subheading: "A project-based, instructor-led curriculum backed by a published outcomes report — taught by engineers from companies you've heard of.",
          primaryCta: { text: "Apply for the Next Cohort", href: "#apply" },
          secondaryCta: { text: "Watch the Info Session", href: "#video" },
          imageSeed: "codeforge-premium-hero",
          imageAlt: "CodeForge Academy students pair-programming",
          textColor: "#e2e8f0",
          mutedColor: "#94a3b8",
          accentColor: "#22d3ee",
        },
        {
          type: "video",
          heading: "See a Day in the Life at CodeForge",
          subheading: "A short look inside our classroom, our teaching model, and our grads.",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          alt: "CodeForge Academy campus tour video",
          bg: "#0f172a",
          textColor: "#e2e8f0",
          mutedColor: "#94a3b8",
        },
        {
          type: "stats",
          items: [
            { value: "1,400+", label: "Graduates since 2019" },
            { value: "91%", label: "Employed within 6 months" },
            { value: "$78K", label: "Average starting salary" },
            { value: "4.9/5", label: "Average student rating" },
          ],
          accentColor: "#22d3ee",
          textColor: "#e2e8f0",
          mutedColor: "#94a3b8",
        },
        {
          type: "grid",
          heading: "A Curriculum Built With Hiring Partners",
          columns: 3,
          items: [
            { iconName: "BookOpen", title: "Weeks 1–4: Web Foundations", text: "HTML, CSS, JavaScript, Git, and command-line fundamentals." },
            { iconName: "Zap", title: "Weeks 5–8: Full-Stack Engineering", text: "React, Node.js, PostgreSQL, and REST/GraphQL API design." },
            { iconName: "Briefcase", title: "Weeks 9–12: Capstone & Careers", text: "A team capstone, technical interview prep, and 1:1 career coaching." },
          ],
          accentColor: "#22d3ee",
          textColor: "#e2e8f0",
          mutedColor: "#94a3b8",
        },
        {
          type: "testimonials",
          heading: "Hear From Our Graduates",
          items: [
            { quote: "I had zero coding background. Fourteen weeks after graduating I was working as a front-end engineer at a Series B startup.", name: "Maya T.", role: "CodeForge Grad, Cohort 14" },
            { quote: "The instructors actually worked in the industry — every lesson felt relevant to what hiring managers were asking me in interviews.", name: "Devon R.", role: "CodeForge Grad, Cohort 11" },
            { quote: "The career coaching alone was worth the tuition. I had three offers within two months of graduating.", name: "Priyanka S.", role: "CodeForge Grad, Cohort 16" },
          ],
          cardBg: "#0f172a",
          textColor: "#e2e8f0",
          mutedColor: "#94a3b8",
        },
        {
          type: "pricing",
          heading: "Choose How You Pay",
          subheading: "Every plan includes the full 12-week curriculum, career coaching, and lifetime alumni access.",
          tiers: [
            { name: "Upfront", price: "$14,900", period: "one-time", features: ["Full 12-week curriculum", "1:1 career coaching", "Lifetime alumni network access", "5% tuition discount"], cta: { text: "Choose Upfront", href: "#apply" } },
            { name: "Income Share", price: "$0", period: "until hired", features: ["Full 12-week curriculum", "Pay 12% of salary for 24 months after hire", "Pay nothing if you don't get hired", "1:1 career coaching"], cta: { text: "Choose Income Share", href: "#apply" }, highlighted: true },
            { name: "Monthly Plan", price: "$1,350", period: "/mo for 12 months", features: ["Full 12-week curriculum", "1:1 career coaching", "No interest financing", "Lifetime alumni network access"], cta: { text: "Choose Monthly", href: "#apply" } },
          ],
          accentColor: "#22d3ee",
          textColor: "#e2e8f0",
          mutedColor: "#94a3b8",
        },
        {
          type: "footer",
          brand: "CodeForge Academy",
          menu: [{ label: "Curriculum" }, { label: "Outcomes Report" }, { label: "Admissions" }, { label: "Careers" }],
          links: [{ provider: "linkedin" }, { provider: "instagram" }, { provider: "youtube" }],
          copyright: "© CodeForge Academy. All rights reserved.",
          bg: "#0a0e17",
        },
      ],
    },
    {
      name: "Brightpath Scholars — Online Bachelor's Degree Program Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "An accredited university program page combining navigation, outcomes data, a program directory, alumni testimonials, and tuition plans — designed for prospective online degree students.",
      pageStyle: { backgroundColor: "#0f1b3d", color: "#f1f5f9", htmlTitle: "Brightpath Scholars" },
      sections: [
        {
          type: "menubar",
          brand: "Brightpath Scholars",
          links: [{ label: "Programs" }, { label: "Admissions" }, { label: "Financial Aid" }, { label: "Outcomes" }],
          cta: { text: "Request Info", href: "#apply" },
          bg: "#0f1b3d",
          textColor: "#f1f5f9",
          accentColor: "#fbbf24",
        },
        {
          type: "hero",
          eyebrow: "REGIONALLY ACCREDITED · 100% ONLINE",
          heading: "Earn Your Bachelor's Degree, On Your Schedule",
          subheading: "Brightpath Scholars brings a full university experience online — live faculty, real classmates, and a diploma employers recognize.",
          primaryCta: { text: "Request Information", href: "#apply" },
          secondaryCta: { text: "Explore Programs", href: "#programs" },
          imageSeed: "brightpath-campus-online",
          imageAlt: "Student attending an online Brightpath Scholars lecture",
          textColor: "#f1f5f9",
          mutedColor: "#b8c2d9",
          accentColor: "#fbbf24",
        },
        {
          type: "stats",
          items: [
            { value: "94%", label: "Course completion rate" },
            { value: "$61K", label: "Average grad starting salary" },
            { value: "12,000+", label: "Enrolled students nationwide" },
            { value: "1:15", label: "Faculty-to-student ratio" },
          ],
          accentColor: "#fbbf24",
          textColor: "#f1f5f9",
          mutedColor: "#b8c2d9",
        },
        {
          type: "grid",
          heading: "Choose Your Program",
          columns: 3,
          items: [
            { iconName: "Briefcase", title: "B.S. in Business Administration", text: "Core business fundamentals with tracks in marketing, finance, and management." },
            { iconName: "Globe", title: "B.A. in Communications", text: "Media, public relations, and digital storytelling for the modern workplace." },
            { iconName: "GraduationCap", title: "B.S. in Health Sciences", text: "A foundation for careers in healthcare administration and public health." },
          ],
          accentColor: "#fbbf24",
          textColor: "#f1f5f9",
          mutedColor: "#b8c2d9",
        },
        {
          type: "testimonials",
          heading: "What Our Graduates Say",
          items: [
            { quote: "Working full-time and raising two kids, I never thought I'd finish my degree. Brightpath's night classes made it possible.", name: "Renata C.", role: "B.S. Business Administration, '24" },
            { quote: "My advisor knew my name and my goals from week one. It didn't feel like a faceless online program at all.", name: "Tobias M.", role: "B.A. Communications, '23" },
          ],
          cardBg: "#16234a",
          textColor: "#f1f5f9",
          mutedColor: "#b8c2d9",
        },
        {
          type: "pricing",
          heading: "Tuition & Payment Plans",
          subheading: "Federal financial aid, employer tuition assistance, and payment plans are available for every program.",
          tiers: [
            { name: "Per Credit", price: "$389", period: "/credit hour", features: ["Pay only for the credits you take", "Transfer up to 90 credits", "Access to all student services"], cta: { text: "See Per-Credit Details", href: "#apply" } },
            { name: "Flat-Rate Term", price: "$3,250", period: "/term (12+ credits)", features: ["Unlimited credits within the term", "Priority academic advising", "Free tutoring & writing center access"], cta: { text: "Choose Flat-Rate", href: "#apply" }, highlighted: true },
            { name: "Employer Partner", price: "Custom", period: "pricing", features: ["Discounted tuition through partner employers", "Dedicated corporate advisor", "Flexible start dates"], cta: { text: "Check Employer Eligibility", href: "#apply" } },
          ],
          accentColor: "#fbbf24",
          textColor: "#f1f5f9",
          mutedColor: "#b8c2d9",
        },
        {
          type: "iconrow",
          heading: "Accredited & Supported",
          items: [
            { iconName: "Award", label: "Regionally Accredited" },
            { iconName: "Wallet", label: "Federal Financial Aid Eligible" },
            { iconName: "Users", label: "Dedicated Academic Advisor" },
            { iconName: "BookOpen", label: "Free Tutoring & Library Access" },
          ],
          accentColor: "#fbbf24",
          textColor: "#f1f5f9",
          mutedColor: "#b8c2d9",
        },
        {
          type: "footer",
          brand: "Brightpath Scholars",
          menu: [{ label: "Programs" }, { label: "Admissions" }, { label: "Financial Aid" }, { label: "Contact" }],
          links: [{ provider: "facebook" }, { provider: "linkedin" }, { provider: "youtube" }],
          copyright: "© Brightpath Scholars. All rights reserved.",
          bg: "#0a1330",
        },
      ],
    },
    {
      name: "Cohort Enrollment Confirmation Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A clean confirmation email that welcomes a new bootcamp student into their cohort, with key dates and a calendar-add call to action.",
      pageStyle: { backgroundColor: "#f0f9ff", color: "#0c1a2b", htmlTitle: "You're Enrolled — CodeForge Academy" },
      sections: [
        {
          type: "hero",
          heading: "You're In, Jordan — Welcome to Cohort 22!",
          subheading: "Your seat in the Full-Stack Engineering bootcamp is confirmed. Classes begin Monday, September 14.",
          accentColor: "#0284c7",
          mutedColor: "#64748b",
        },
        {
          type: "table",
          heading: "Your Cohort Details",
          headers: ["Detail", "Info"],
          rows: [
            ["Cohort", "Full-Stack Engineering — Cohort 22"],
            ["Start Date", "Monday, September 14, 2026"],
            ["Schedule", "Mon–Fri, 9:00 AM–5:00 PM ET"],
            ["Orientation", "Friday, September 11, 2026 at 10:00 AM ET"],
          ],
        },
        {
          type: "cta",
          heading: "Add Orientation to Your Calendar",
          subheading: "Don't miss your first live session with instructors and classmates.",
          cta: { text: "Add to Calendar", href: "#calendar" },
          bg: "#0284c7",
        },
        {
          type: "footer",
          brand: "CodeForge Academy",
          copyright: "© CodeForge Academy. Questions? Reply to this email.",
          bg: "#0c1a2b",
        },
      ],
    },
    {
      name: "Live Coaching Session Reminder Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A warm reminder email for an upcoming live coaching webinar, with session details and a one-click join call to action.",
      pageStyle: { backgroundColor: "#fffaf0", color: "#3f3222", htmlTitle: "Your Session Starts Tomorrow" },
      sections: [
        {
          type: "hero",
          eyebrow: "TOMORROW AT 6:00 PM ET",
          heading: "Your Live Session With Coach Elena Starts Tomorrow",
          subheading: "\"Turning Your Career Plan Into Action\" — bring your questions, it's a live Q&A.",
          accentColor: "#b45309",
          mutedColor: "#8a7860",
        },
        {
          type: "richtext",
          heading: "What to Expect",
          paragraphs: [
            "We'll cover how to set 90-day goals you'll actually follow through on, plus open the floor for live coaching on whatever's top of mind for you right now.",
            "This session is recorded, but showing up live is the only way to get your question answered on air.",
          ],
          mutedColor: "#8a7860",
        },
        {
          type: "cta",
          heading: "Save Your Spot in the Live Room",
          subheading: "Sessions typically fill up — join a few minutes early to get settled.",
          cta: { text: "Join the Live Session", href: "#join" },
          bg: "#b45309",
        },
        {
          type: "footer",
          brand: "Summit Mentorship",
          copyright: "© Summit Mentorship. Manage your session reminders anytime.",
          bg: "#3f2d1c",
        },
      ],
    },
    {
      name: "Course Completion & Certificate Email",
      kind: "EMAIL",
      tier: "premium",
      description: "A celebratory course-completion email that delivers a shareable certificate, progress stats, a graduate testimonial, and recommended next courses — built for automated completion flows.",
      pageStyle: { backgroundColor: "#f0fdfa", color: "#134e4a", htmlTitle: "You Did It! Certificate Enclosed" },
      sections: [
        {
          type: "hero",
          eyebrow: "CONGRATULATIONS",
          heading: "You've Completed Conversational Spanish, Level 3!",
          subheading: "Your certificate is ready to download and share — you've earned it.",
          primaryCta: { text: "Download My Certificate", href: "#certificate" },
          accentColor: "#0d9488",
          mutedColor: "#5f8a86",
        },
        {
          type: "stats",
          items: [
            { value: "64", label: "Lessons completed" },
            { value: "38", label: "Days of your learning streak" },
            { value: "1,240", label: "New words learned" },
          ],
          accentColor: "#0d9488",
          textColor: "#134e4a",
          mutedColor: "#5f8a86",
        },
        {
          type: "testimonials",
          items: [
            { quote: "Finishing Level 3 felt impossible in January. Lingora's daily reminders and short lessons made it stick.", name: "Amara O.", role: "Lingora Learner" },
          ],
          cardBg: "#ffffff",
          textColor: "#134e4a",
          mutedColor: "#5f8a86",
        },
        {
          type: "grid",
          heading: "Keep Your Streak Going",
          columns: 3,
          items: [
            { iconName: "BookOpen", title: "Conversational Spanish, Level 4", text: "Take on more complex grammar and real-world conversation practice." },
            { iconName: "Users", title: "Live Conversation Club", text: "Practice everything you've learned with fellow Level 3 graduates." },
            { iconName: "Globe", title: "Start a Second Language", text: "Use your Lingora streak momentum to begin French, Japanese, or Italian." },
          ],
          accentColor: "#0d9488",
        },
        {
          type: "cta",
          heading: "Ready for Level 4?",
          subheading: "Your streak carries over — pick up right where you left off.",
          cta: { text: "Continue to Level 4", href: "#continue" },
          bg: "#0d9488",
          textColor: "#f0fdfa",
          mutedColor: "#ccfbf1",
        },
        {
          type: "footer",
          brand: "Lingora",
          copyright: "© Lingora. Share your certificate — tag us and we'll celebrate with you.",
          bg: "#0f2e2c",
        },
      ],
    },
    {
      name: "Free Trial Lesson Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A short, focused opt-in page offering a free trial lesson to capture new language-learner signups.",
      pageStyle: { backgroundColor: "#ecfeff", color: "#083344", htmlTitle: "Try Your First Lesson Free" },
      sections: [
        {
          type: "hero",
          eyebrow: "NO CREDIT CARD NEEDED",
          heading: "Try Your First Lingora Lesson, Free",
          subheading: "Answer three quick questions and we'll build a 10-minute lesson matched to your level and goals.",
          accentColor: "#0891b2",
          mutedColor: "#4b6b73",
        },
        {
          type: "form",
          heading: "Get Your Free Lesson",
          fields: [
            { kind: "text", label: "First Name", name: "firstName", placeholder: "Jane", required: true },
            { kind: "select", label: "Language You Want to Learn", name: "language", options: ["Spanish", "French", "Japanese", "Italian", "German"], required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
          ],
          submitLabel: "Send Me My Free Lesson",
          accentColor: "#0891b2",
        },
        {
          type: "footer",
          brand: "Lingora",
          copyright: "© Lingora.",
          bg: "#083344",
        },
      ],
    },
    {
      name: "Program Syllabus Download Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A trust-building opt-in page for prospective students to download a full program syllabus in exchange for their contact information.",
      pageStyle: { backgroundColor: "#fdf6ec", color: "#3b0a0a", htmlTitle: "Download the Program Syllabus" },
      sections: [
        {
          type: "hero",
          eyebrow: "B.S. IN BUSINESS ADMINISTRATION",
          heading: "See Exactly What You'll Study, Course by Course",
          subheading: "Download the full syllabus — every course, credit requirement, and elective option.",
          accentColor: "#9f1239",
          mutedColor: "#7a5b4a",
        },
        {
          type: "form",
          heading: "Send Me the Syllabus",
          fields: [
            { kind: "text", label: "Full Name", name: "name", placeholder: "Jordan Smith", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
          ],
          submitLabel: "Download the Syllabus",
          accentColor: "#9f1239",
        },
        {
          type: "iconrow",
          items: [
            { iconName: "Award", label: "Regionally Accredited" },
            { iconName: "Clock", label: "Finish in as little as 2.5 years" },
            { iconName: "Wallet", label: "Financial Aid Available" },
          ],
          accentColor: "#9f1239",
        },
        {
          type: "footer",
          brand: "Brightpath Scholars",
          copyright: "© Brightpath Scholars.",
          bg: "#3b0a0a",
        },
      ],
    },
    {
      name: "Next Cohort Waitlist Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A minimal waitlist opt-in page for a mentorship program's next cohort, built to capture leads before enrollment opens.",
      pageStyle: { backgroundColor: "#fdf8f3", color: "#3f2d1c", htmlTitle: "Join the Waitlist" },
      sections: [
        {
          type: "hero",
          eyebrow: "COHORT 9 — ENROLLMENT OPENS SOON",
          heading: "Be First in Line for Our Next Coaching Cohort",
          subheading: "Summit Mentorship cohorts fill within days of opening. Join the waitlist to get 24-hour early access.",
          accentColor: "#92400e",
          mutedColor: "#8a7360",
        },
        {
          type: "form",
          heading: "Join the Waitlist",
          subheading: "We'll email you the moment enrollment opens — no spam, ever.",
          fields: [{ kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true }],
          submitLabel: "Join the Waitlist",
          accentColor: "#92400e",
        },
        {
          type: "stats",
          items: [
            { value: "9", label: "Cohorts run since 2021" },
            { value: "87%", label: "Members who hit their 90-day goal" },
            { value: "4.8/5", label: "Average member rating" },
          ],
          accentColor: "#92400e",
          textColor: "#3f2d1c",
          mutedColor: "#8a7360",
        },
        {
          type: "footer",
          brand: "Summit Mentorship",
          copyright: "© Summit Mentorship.",
          bg: "#2d2013",
        },
      ],
    },
  ],
};
