import type { CategoryBatch } from "../types";

export const entertainmentBatch: CategoryBatch = {
  category: "Entertainment, Events & Nightlife",
  specs: [
    {
      name: "Nocturne Saturdays — Nightclub Night Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A moody, neon-lit landing page for promoting a weekly nightclub night — hero, DJ lineup grid, and a direct call to reserve a table.",
      pageStyle: { backgroundColor: "#0a0a12", color: "#f5f3ff", htmlTitle: "Nocturne Saturdays" },
      sections: [
        {
          type: "hero",
          eyebrow: "EVERY SATURDAY NIGHT",
          heading: "Nocturne Saturdays: The City's Loudest Night Out",
          subheading: "Resident DJs, bottle service, and a sound system built to move the room. Doors at 10PM.",
          primaryCta: { text: "Reserve a Table", href: "#reserve" },
          imageSeed: "nocturne-dancefloor-hero",
          imageAlt: "Nocturne dance floor under neon lights",
          accentColor: "#e930ff",
          textColor: "#f5f3ff",
          mutedColor: "#c4b5fd",
        },
        {
          type: "grid",
          heading: "This Week's Lineup",
          columns: 3,
          items: [
            { imageSeed: "nocturne-dj-vex", title: "DJ VEX", text: "Deep house, midnight to 2AM" },
            { imageSeed: "nocturne-dj-mira", title: "MIRA", text: "Techno, 2AM to close" },
            { imageSeed: "nocturne-resident-kato", title: "KATO", text: "Opening set, 10PM to midnight" },
          ],
          accentColor: "#e930ff",
          textColor: "#f5f3ff",
          mutedColor: "#c4b5fd",
        },
        {
          type: "cta",
          heading: "Skip the Line — Reserve a Table",
          subheading: "VIP tables include a dedicated host and bottle service.",
          cta: { text: "Reserve Now", href: "#reserve" },
          bg: "#e930ff",
          textColor: "#0a0a12",
        },
        {
          type: "footer",
          brand: "Nocturne",
          links: [{ provider: "instagram" }, { provider: "tiktok" }],
          copyright: "© Nocturne Nightclub. 21+ after 9PM.",
          bg: "#0a0a12",
        },
      ],
    },
    {
      name: "Static Mic Comedy Club — Weekend Showcase Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A punchy, high-energy landing page for a stand-up comedy showcase featuring headliners, showtimes, and a ticket CTA.",
      pageStyle: { backgroundColor: "#161312", color: "#fef3c7", htmlTitle: "Static Mic Comedy Club" },
      sections: [
        {
          type: "hero",
          eyebrow: "THIS WEEKEND ONLY",
          heading: "Static Mic Presents: The Saturday Showcase",
          subheading: "Four headliners. One stage. Doors open 7:30, show starts 8 sharp.",
          primaryCta: { text: "Get Tickets", href: "#tickets" },
          imageSeed: "static-mic-stage-hero",
          imageAlt: "Comedian performing under a single spotlight",
          accentColor: "#14b8a6",
          textColor: "#fef3c7",
          mutedColor: "#d6d3d1",
        },
        {
          type: "grid",
          heading: "Who's On Tonight",
          columns: 4,
          items: [
            { imageSeed: "comedian-nora-vance", title: "Nora Vance", text: "Headliner — Netflix special \"Overshare\"" },
            { imageSeed: "comedian-desmond-oke", title: "Desmond Oke", text: "Feature act" },
            { imageSeed: "comedian-ruth-chen", title: "Ruth Chen", text: "Feature act" },
            { imageSeed: "comedian-mc-jonesy", title: "Jonesy", text: "Host / MC" },
          ],
          accentColor: "#14b8a6",
          textColor: "#fef3c7",
          mutedColor: "#d6d3d1",
        },
        {
          type: "cta",
          heading: "Seats Are Going Fast",
          subheading: "Doors close once the room hits capacity — no re-entry.",
          cta: { text: "Buy Tickets", href: "#tickets" },
          bg: "#f59e0b",
          textColor: "#161312",
        },
        {
          type: "footer",
          brand: "Static Mic Comedy Club",
          menu: [{ label: "Showtimes" }, { label: "Book a Table" }],
          links: [{ provider: "instagram" }, { provider: "youtube" }],
          copyright: "© Static Mic Comedy Club.",
          bg: "#101014",
        },
      ],
    },
    {
      name: "Wildfire Music Festival — Full Lineup & Tickets Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A festival-scale landing page with navigation, a countdown to gates-open, a photo gallery, tiered ticket pricing, and fan testimonials — everything needed to sell out a multi-day music festival.",
      pageStyle: { backgroundColor: "#1a0800", color: "#fff7ed", htmlTitle: "Wildfire Music Festival" },
      sections: [
        {
          type: "menubar",
          brand: "Wildfire Festival",
          links: [{ label: "Lineup" }, { label: "Tickets" }, { label: "Camping" }, { label: "FAQ" }],
          cta: { text: "Get Tickets", href: "#tickets" },
          bg: "#1a0800",
          textColor: "#fff7ed",
          accentColor: "#f97316",
        },
        {
          type: "hero",
          eyebrow: "AUGUST 14–16, 2026 · SUNBELT VALLEY",
          heading: "Three Days. Five Stages. One Wildfire.",
          subheading: "60+ artists across desert-valley stages, all-night camping, and sunrise sets you'll be talking about for years.",
          primaryCta: { text: "Get Tickets", href: "#tickets" },
          secondaryCta: { text: "See Full Lineup", href: "#lineup" },
          imageSeed: "wildfire-main-stage-hero",
          imageAlt: "Crowd at Wildfire Festival main stage at sunset",
          accentColor: "#f97316",
          textColor: "#fff7ed",
          mutedColor: "#fdba74",
        },
        {
          type: "countdown",
          heading: "Gates Open In",
          subheading: "Early-entry campers get first pick of tent sites.",
          targetDate: "2026-08-14T12:00:00",
          bg: "#2b0a0a",
          textColor: "#fff7ed",
          mutedColor: "#fdba74",
        },
        {
          type: "gallery",
          heading: "Last Year at Wildfire",
          images: [
            { seed: "wildfire-gallery-1", alt: "Fans dancing at golden hour" },
            { seed: "wildfire-gallery-2", alt: "Pyrotechnics over the main stage" },
            { seed: "wildfire-gallery-3", alt: "Campground at sunrise" },
            { seed: "wildfire-gallery-4", alt: "DJ set under string lights" },
          ],
          textColor: "#fff7ed",
          bg: "#1a0800",
        },
        {
          type: "pricing",
          heading: "Choose Your Pass",
          subheading: "Prices increase after each release tier sells out.",
          tiers: [
            {
              name: "GA Weekend",
              price: "$249",
              period: "3-day pass",
              features: ["Access to all 5 stages", "General camping included", "Festival app & schedule"],
              cta: { text: "Get GA Pass", href: "#tickets" },
            },
            {
              name: "VIP Weekend",
              price: "$549",
              period: "3-day pass",
              features: ["Front-of-stage VIP viewing", "Air-conditioned lounge & shaded seating", "Dedicated VIP entrance & parking", "Premium restrooms"],
              cta: { text: "Get VIP Pass", href: "#tickets" },
              highlighted: true,
            },
            {
              name: "Artist Pass",
              price: "$1,200",
              period: "3-day pass",
              features: ["Side-stage viewing at every set", "Backstage catering access", "Meet & greet lottery entry", "VIP + GA perks included"],
              cta: { text: "Apply for Artist Pass", href: "#tickets" },
            },
          ],
          accentColor: "#f97316",
          textColor: "#fff7ed",
          mutedColor: "#fdba74",
          bg: "#1a0800",
        },
        {
          type: "testimonials",
          heading: "Wildfire Changes You",
          items: [
            { quote: "I've been to a dozen festivals and nothing beats the sunrise set at Wildfire. Life event, not just a show.", name: "Priya M.", role: "3-time attendee" },
            { quote: "The camping setup alone is worth the ticket price. Felt safe, organized, and the vibe was unreal.", name: "Jonah T.", role: "First-time attendee" },
          ],
          cardBg: "#2b0a0a",
          textColor: "#fff7ed",
          mutedColor: "#fdba74",
        },
        {
          type: "footer",
          brand: "Wildfire Music Festival",
          menu: [{ label: "Lineup" }, { label: "Camping Info" }, { label: "Accessibility" }, { label: "Contact" }],
          links: [{ provider: "instagram" }, { provider: "tiktok" }, { provider: "x" }, { provider: "youtube" }],
          copyright: "© Wildfire Music Festival. All rights reserved.",
          bg: "#1a0800",
        },
      ],
    },
    {
      name: "Lumière Premiere Night — Streaming Launch Event Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A cinematic, dark-mode landing page for a red-carpet film or streaming premiere — trailer video, cast grid, VIP ticket tiers, and press-quote testimonials.",
      pageStyle: { backgroundColor: "#0b0b0d", color: "#f5f5f0", htmlTitle: "Lumière Premiere Night" },
      sections: [
        {
          type: "menubar",
          brand: "Lumière Premiere",
          links: [{ label: "The Film" }, { label: "Cast" }, { label: "Tickets" }, { label: "Press" }],
          cta: { text: "Reserve Seats", href: "#tickets" },
          bg: "#0b0b0d",
          textColor: "#f5f5f0",
          accentColor: "#d4af37",
        },
        {
          type: "hero",
          eyebrow: "WORLD PREMIERE · SEPTEMBER 18, 2026",
          heading: "Midnight Hour — Live on the Red Carpet",
          subheading: "Be among the first to see the film everyone will be talking about, followed by a live Q&A with the cast.",
          primaryCta: { text: "Reserve Your Seat", href: "#tickets" },
          secondaryCta: { text: "Watch the Trailer", href: "#trailer" },
          imageSeed: "lumiere-red-carpet-hero",
          imageAlt: "Red carpet arrivals outside the Lumière Theatre",
          accentColor: "#d4af37",
          textColor: "#f5f5f0",
          mutedColor: "#a8a29e",
        },
        {
          type: "video",
          heading: "Watch the Official Trailer",
          subheading: "Midnight Hour — in theaters and streaming everywhere September 18.",
          videoUrl: "https://example.com/midnight-hour-trailer.mp4",
          alt: "Midnight Hour official trailer",
          bg: "#111113",
          textColor: "#f5f5f0",
          mutedColor: "#a8a29e",
        },
        {
          type: "grid",
          heading: "Meet the Cast",
          columns: 3,
          items: [
            { imageSeed: "cast-elena-marsh", title: "Elena Marsh", text: "as Detective Wren" },
            { imageSeed: "cast-tobias-reyes", title: "Tobias Reyes", text: "as Sable" },
            { imageSeed: "cast-director-hana-ito", title: "Hana Ito", text: "Director" },
          ],
          accentColor: "#d4af37",
          textColor: "#f5f5f0",
          mutedColor: "#a8a29e",
        },
        {
          type: "pricing",
          heading: "Premiere Night Passes",
          subheading: "Every pass includes the screening — VIP adds the after-party.",
          tiers: [
            {
              name: "Screening Pass",
              price: "$45",
              features: ["Reserved theater seating", "Digital program", "Exclusive premiere poster"],
              cta: { text: "Get Screening Pass", href: "#tickets" },
            },
            {
              name: "Red Carpet VIP",
              price: "$180",
              features: ["Priority red-carpet viewing", "Reserved front-section seating", "Cast Q&A access", "After-party admission"],
              cta: { text: "Get VIP Pass", href: "#tickets" },
              highlighted: true,
            },
          ],
          accentColor: "#d4af37",
          textColor: "#f5f5f0",
          mutedColor: "#a8a29e",
          bg: "#111113",
        },
        {
          type: "testimonials",
          heading: "Early Buzz",
          items: [
            { quote: "Midnight Hour is the most confident directorial debut of the year.", name: "Rosa Delgado", role: "Film critic, Reel Weekly" },
            { quote: "A premiere night worth dressing up for — the Q&A alone was unforgettable.", name: "Priya S.", role: "Premiere attendee" },
          ],
          cardBg: "#111113",
          textColor: "#f5f5f0",
          mutedColor: "#a8a29e",
        },
        {
          type: "footer",
          brand: "Lumière Premiere",
          links: [{ provider: "instagram" }, { provider: "x" }, { provider: "youtube" }],
          copyright: "© Lumière Premiere Events. All rights reserved.",
          bg: "#0b0b0d",
        },
      ],
    },
    {
      name: "Wildfire Festival — Ticket Purchase Confirmation Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A clean order-confirmation email confirming a festival ticket purchase with pass details and a link to manage the order.",
      pageStyle: { backgroundColor: "#fff7ed", color: "#1a0800", htmlTitle: "Your Wildfire Pass is Confirmed" },
      sections: [
        {
          type: "hero",
          heading: "You're In, Priya!",
          subheading: "Your Wildfire Festival VIP Weekend Pass is confirmed for August 14–16, 2026.",
          accentColor: "#f97316",
          mutedColor: "#78350f",
        },
        {
          type: "table",
          heading: "Order Summary",
          headers: ["Item", "Qty", "Price"],
          rows: [
            ["VIP Weekend Pass", "1", "$549.00"],
            ["Camping Add-On", "1", "$65.00"],
            ["Booking Fee", "—", "$12.00"],
          ],
        },
        {
          type: "cta",
          heading: "Manage Your Order",
          subheading: "Download your mobile ticket and add camping upgrades anytime before the gates open.",
          cta: { text: "View My Tickets", href: "#tickets" },
          bg: "#f97316",
          textColor: "#1a0800",
        },
        {
          type: "footer",
          brand: "Wildfire Music Festival",
          copyright: "© Wildfire Music Festival. Questions? Reply to this email.",
          bg: "#1a0800",
        },
      ],
    },
    {
      name: "Nocturne — Event Reminder Email with Countdown",
      kind: "EMAIL",
      tier: "quick",
      description: "A moody event-reminder email with a live countdown to doors-open, sent to reserved-table guests the day before the show.",
      pageStyle: { backgroundColor: "#0a0a12", color: "#f5f3ff", htmlTitle: "Your Table is Waiting" },
      sections: [
        {
          type: "hero",
          eyebrow: "TOMORROW NIGHT",
          heading: "Your Table at Nocturne is Confirmed",
          subheading: "Doors open at 10PM — arrive by 11 to keep your reserved table.",
          accentColor: "#e930ff",
          mutedColor: "#c4b5fd",
        },
        {
          type: "countdown",
          heading: "Doors Open In",
          targetDate: "2026-09-05T22:00:00",
          bg: "#14131c",
          textColor: "#f5f3ff",
          mutedColor: "#c4b5fd",
        },
        {
          type: "cta",
          heading: "Need to Update Your Reservation?",
          subheading: "Party size changes must be made at least 4 hours before doors.",
          cta: { text: "Manage Reservation", href: "#manage" },
          bg: "#e930ff",
          textColor: "#0a0a12",
        },
        {
          type: "footer",
          brand: "Nocturne",
          copyright: "© Nocturne Nightclub. 21+ after 9PM.",
          bg: "#0a0a12",
        },
      ],
    },
    {
      name: "Lumière Premiere — Schedule & Red Carpet Timeline Email",
      kind: "EMAIL",
      tier: "premium",
      description: "A richly detailed premiere-night email walking VIP pass holders through the red-carpet timeline, cast Q&A schedule, and after-party details.",
      pageStyle: { backgroundColor: "#0b0b0d", color: "#f5f5f0", htmlTitle: "Your Premiere Night Itinerary" },
      sections: [
        {
          type: "hero",
          eyebrow: "SEPTEMBER 18, 2026",
          heading: "Here's Your Premiere Night Itinerary",
          subheading: "Everything you need for red-carpet arrival, the screening, and the after-party.",
          accentColor: "#d4af37",
          mutedColor: "#a8a29e",
        },
        {
          type: "richtext",
          heading: "Before You Arrive",
          paragraphs: [
            "Doors open at 6:30PM for red-carpet arrivals. VIP pass holders should check in at the west entrance, where a Lumière host will direct you to your reserved viewing area.",
            "Formal or cocktail attire is recommended — this is a red-carpet event with press and photographers on-site.",
          ],
          mutedColor: "#a8a29e",
        },
        {
          type: "table",
          heading: "Tonight's Schedule",
          headers: ["Time", "What's Happening"],
          rows: [
            ["6:30 PM", "Red carpet arrivals & press line"],
            ["7:30 PM", "Doors close, screening begins"],
            ["9:45 PM", "Live cast Q&A with Elena Marsh & Tobias Reyes"],
            ["10:30 PM", "After-party opens (VIP pass required)"],
          ],
        },
        {
          type: "grid",
          heading: "Who You'll See",
          columns: 3,
          items: [
            { imageSeed: "cast-elena-marsh-2", title: "Elena Marsh", text: "as Detective Wren" },
            { imageSeed: "cast-tobias-reyes-2", title: "Tobias Reyes", text: "as Sable" },
            { imageSeed: "cast-director-hana-ito-2", title: "Hana Ito", text: "Director, live Q&A host" },
          ],
        },
        {
          type: "cta",
          heading: "Add a Guest or Update Details",
          subheading: "Guest changes must be submitted at least 24 hours before the event.",
          cta: { text: "Manage My Pass", href: "#manage" },
          bg: "#d4af37",
          textColor: "#0b0b0d",
        },
        {
          type: "footer",
          brand: "Lumière Premiere",
          copyright: "© Lumière Premiere Events.",
          bg: "#0b0b0d",
        },
      ],
    },
    {
      name: "Nocturne — Guest List Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A short, moody opt-in page for joining the Nocturne guest list to skip cover charges and get first access to table reservations.",
      pageStyle: { backgroundColor: "#0a0a12", color: "#f5f3ff", htmlTitle: "Join the Nocturne Guest List" },
      sections: [
        {
          type: "hero",
          eyebrow: "SKIP THE LINE",
          heading: "Get On the Nocturne Guest List",
          subheading: "Free cover before 11PM, first access to table reservations, and word on secret pop-up nights.",
          accentColor: "#22d3ee",
          mutedColor: "#c4b5fd",
        },
        {
          type: "form",
          heading: "Join the Guest List",
          subheading: "We text you the week's lineup — nothing else.",
          fields: [
            { kind: "text", label: "Full Name", name: "fullName", placeholder: "Jordan Ade", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
          ],
          submitLabel: "Join the Guest List",
          accentColor: "#22d3ee",
        },
        {
          type: "footer",
          brand: "Nocturne",
          copyright: "© Nocturne Nightclub. 21+ after 9PM.",
          bg: "#0a0a12",
        },
      ],
    },
    {
      name: "Wildfire Festival — Early-Bird Ticket Alert Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A quick opt-in page for fans who want a heads-up the moment early-bird Wildfire Festival tickets go on sale, before prices increase.",
      pageStyle: { backgroundColor: "#1a0800", color: "#fff7ed", htmlTitle: "Get the Early-Bird Alert" },
      sections: [
        {
          type: "hero",
          eyebrow: "TICKETS DROP SOON",
          heading: "Be First to Know When Early-Bird Tickets Go Live",
          subheading: "Early-bird passes sell out in hours. Get an alert the moment they open — before the price jumps.",
          accentColor: "#f97316",
          mutedColor: "#fdba74",
        },
        {
          type: "form",
          heading: "Get the Early-Bird Alert",
          fields: [{ kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true }],
          submitLabel: "Notify Me First",
          accentColor: "#f97316",
        },
        {
          type: "iconrow",
          items: [
            { iconName: "Ticket", label: "First access to early-bird pricing" },
            { iconName: "Mail", label: "One heads-up email, no spam" },
            { iconName: "Music", label: "Full lineup reveal included" },
          ],
          accentColor: "#f97316",
          textColor: "#fff7ed",
          mutedColor: "#fdba74",
        },
        {
          type: "footer",
          brand: "Wildfire Music Festival",
          copyright: "© Wildfire Music Festival.",
          bg: "#1a0800",
        },
      ],
    },
    {
      name: "Static Mic Comedy Club — Ticket Drop Notification Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A lightweight opt-in page for comedy fans who want to be notified the instant tickets go on sale for the next Static Mic showcase.",
      pageStyle: { backgroundColor: "#161312", color: "#fef3c7", htmlTitle: "Get Notified When Tickets Drop" },
      sections: [
        {
          type: "hero",
          eyebrow: "NEXT SHOWCASE: TBA",
          heading: "Don't Miss the Next Showcase",
          subheading: "Our shows sell out fast — leave your email and we'll ping you the second tickets go live.",
          accentColor: "#14b8a6",
          mutedColor: "#d6d3d1",
        },
        {
          type: "form",
          heading: "Notify Me",
          fields: [{ kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true }],
          submitLabel: "Notify Me When Tickets Drop",
          accentColor: "#14b8a6",
        },
        {
          type: "footer",
          brand: "Static Mic Comedy Club",
          copyright: "© Static Mic Comedy Club.",
          bg: "#101014",
        },
      ],
    },
  ],
};
