import type { CategoryBatch } from "../types";

export const healthFitnessBatch: CategoryBatch = {
  category: "Health, Fitness & Wellness",
  specs: [
    {
      name: "Forge Athletic Co. — Free Trial Week Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A high-energy landing page for a CrossFit-style gym promoting a free trial week, with a class grid and a bold join-now CTA.",
      pageStyle: { backgroundColor: "#0a0a0a", color: "#fafafa", htmlTitle: "Forge Athletic Co." },
      sections: [
        {
          type: "hero",
          eyebrow: "NO EXCUSES. JUST RESULTS.",
          heading: "Your First Week Is On Us",
          subheading: "Walk into Forge and find out what you're actually capable of. Seven days of unlimited classes — zero commitment.",
          primaryCta: { text: "Claim My Free Week", href: "#trial" },
          imageSeed: "forge-gym-floor-hero",
          imageAlt: "Athletes training on the Forge gym floor",
          accentColor: "#dc2626",
          textColor: "#fafafa",
          mutedColor: "#a3a3a3",
        },
        {
          type: "grid",
          heading: "Classes Running This Week",
          columns: 3,
          items: [
            { iconName: "Flame", title: "Forge Metcon", text: "45 minutes of high-intensity conditioning that never gets easy — and never gets boring.", cta: { text: "Reserve a Spot", href: "#trial" } },
            { iconName: "Dumbbell", title: "Barbell Strength", text: "Squat, press, and pull under the eye of coaches who actually watch your form.", cta: { text: "Reserve a Spot", href: "#trial" } },
            { iconName: "Users", title: "Open Gym", text: "Come work your own program with full access to the floor and equipment.", cta: { text: "Reserve a Spot", href: "#trial" } },
          ],
          accentColor: "#dc2626",
          textColor: "#fafafa",
          mutedColor: "#a3a3a3",
        },
        {
          type: "cta",
          heading: "One Week. Every Class. Completely Free.",
          subheading: "No credit card, no catch — just show up and see if Forge is your gym.",
          cta: { text: "Start My Free Week", href: "#trial" },
          bg: "#dc2626",
          textColor: "#0a0a0a",
          mutedColor: "#3f0d0d",
        },
        {
          type: "footer",
          brand: "Forge Athletic Co.",
          menu: [{ label: "Classes" }, { label: "Coaches" }, { label: "Membership" }],
          links: [{ provider: "instagram" }, { provider: "tiktok" }, { provider: "youtube" }],
          copyright: "© Forge Athletic Co. Train hard. Recover harder.",
          bg: "#0a0a0a",
        },
      ],
    },
    {
      name: "Still Waters Yoga & Wellness — Class Schedule Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A calm, image-light landing page for a boutique yoga studio spotlighting weekly classes and inviting new students to a free first session.",
      pageStyle: { backgroundColor: "#faf7f0", color: "#33422f", htmlTitle: "Still Waters Yoga & Wellness" },
      sections: [
        {
          type: "hero",
          eyebrow: "BREATHE. MOVE. RETURN TO YOURSELF.",
          heading: "A Quieter Kind of Strong",
          subheading: "Still Waters is a neighborhood studio for vinyasa, restorative, and breathwork practice — no experience required, just an open mind.",
          primaryCta: { text: "See This Week's Schedule", href: "#schedule" },
          imageSeed: "still-waters-studio-hero",
          imageAlt: "Sunlit yoga studio with mats laid out in rows",
          accentColor: "#7c9473",
          textColor: "#33422f",
          mutedColor: "#6b7660",
        },
        {
          type: "grid",
          heading: "Find Your Practice",
          columns: 3,
          items: [
            { iconName: "Sun", title: "Morning Vinyasa", text: "A flowing sunrise practice to wake the body before the day gets loud." },
            { iconName: "Moon", title: "Restorative & Yin", text: "Long, supported holds that give the nervous system permission to finally exhale." },
            { iconName: "Leaf", title: "Breathwork Circle", text: "Guided pranayama sessions to steady the mind and settle the breath." },
          ],
          accentColor: "#7c9473",
          textColor: "#33422f",
          mutedColor: "#6b7660",
        },
        {
          type: "cta",
          heading: "Your First Class Is On the House",
          subheading: "Bring a mat, or borrow one of ours — we'll take care of the rest.",
          cta: { text: "Book My First Class", href: "#schedule" },
          bg: "#7c9473",
          textColor: "#faf7f0",
          mutedColor: "#e4ecdf",
        },
        {
          type: "footer",
          brand: "Still Waters Yoga & Wellness",
          menu: [{ label: "Schedule" }, { label: "Teachers" }, { label: "Retreats" }],
          links: [{ provider: "instagram" }, { provider: "facebook" }],
          copyright: "© Still Waters Yoga & Wellness Spa.",
          bg: "#33422f",
        },
      ],
    },
    {
      name: "Forge Athletic Co. — Full Gym & Personal Training Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A rich, multi-section gym landing page with navigation, member stats, class and personal-training offerings, testimonials, membership pricing, and amenities — built for a full-service athletic facility.",
      pageStyle: { backgroundColor: "#111111", color: "#fafafa", htmlTitle: "Forge Athletic Co." },
      sections: [
        {
          type: "menubar",
          brand: "Forge Athletic Co.",
          links: [{ label: "Classes" }, { label: "Personal Training" }, { label: "Coaches" }, { label: "Membership" }],
          cta: { text: "Join Forge", href: "#join" },
          bg: "#111111",
          textColor: "#fafafa",
          accentColor: "#ef4444",
        },
        {
          type: "hero",
          eyebrow: "OKLAHOMA CITY'S HARDEST-WORKING GYM",
          heading: "Built By Coaches. Tested By Athletes.",
          subheading: "Group training, one-on-one coaching, and a community that shows up at 5:30am so you don't have to talk yourself into it.",
          primaryCta: { text: "Start Your Free Week", href: "#join" },
          secondaryCta: { text: "Meet the Coaches", href: "#coaches" },
          imageSeed: "forge-barbell-hero",
          imageAlt: "Coach spotting an athlete during a heavy barbell lift",
          accentColor: "#ef4444",
          textColor: "#fafafa",
          mutedColor: "#a3a3a3",
        },
        {
          type: "stats",
          items: [
            { value: "3,200+", label: "Athletes trained since 2016" },
            { value: "48", label: "Certified coaches on staff" },
            { value: "9", label: "Years serving this community" },
            { value: "4.9/5", label: "Average member rating" },
          ],
          accentColor: "#ef4444",
          textColor: "#fafafa",
          mutedColor: "#a3a3a3",
        },
        {
          type: "grid",
          heading: "Train However You Train Best",
          columns: 3,
          items: [
            { iconName: "Flame", title: "Group Metcon", text: "High-intensity classes capped at 16 athletes so coaches actually coach." },
            { iconName: "Target", title: "1-on-1 Personal Training", text: "A dedicated coach builds your program around your goals and your schedule." },
            { iconName: "Dumbbell", title: "Strength & Powerlifting", text: "Structured barbell cycles for athletes chasing real numbers." },
          ],
          accentColor: "#ef4444",
          textColor: "#fafafa",
          mutedColor: "#a3a3a3",
        },
        {
          type: "testimonials",
          heading: "Members Who Showed Up And Changed",
          items: [
            { quote: "I hadn't worked out in a decade. Eighteen months later I deadlift more than I weigh.", name: "Marcus T.", role: "Member since 2024" },
            { quote: "The coaches noticed my knee was off before I did. That kind of attention is rare.", name: "Priya S.", role: "Personal Training Client" },
            { quote: "Best community I've ever trained with — nobody gets left behind on the whiteboard.", name: "Dana R.", role: "Member since 2022" },
          ],
          cardBg: "#1c1c1c",
          textColor: "#fafafa",
          mutedColor: "#a3a3a3",
        },
        {
          type: "pricing",
          heading: "Membership Built Around You",
          subheading: "Cancel or pause anytime — no long-term contracts.",
          tiers: [
            { name: "Class Pass", price: "$99", period: "/mo", features: ["Unlimited group classes", "Open gym access", "Community events"], cta: { text: "Choose Class Pass", href: "#join" } },
            { name: "All Access", price: "$159", period: "/mo", features: ["Everything in Class Pass", "2 personal training sessions/mo", "Nutrition check-ins"], cta: { text: "Choose All Access", href: "#join" }, highlighted: true },
            { name: "Elite Coaching", price: "$349", period: "/mo", features: ["Unlimited 1-on-1 coaching", "Custom programming", "Priority scheduling"], cta: { text: "Choose Elite Coaching", href: "#join" } },
          ],
          accentColor: "#ef4444",
          textColor: "#fafafa",
          mutedColor: "#a3a3a3",
        },
        {
          type: "iconrow",
          heading: "What's Included at Every Level",
          items: [
            { iconName: "Users", label: "Certified Coaches" },
            { iconName: "Clock", label: "Open 5am–9pm Daily" },
            { iconName: "Award", label: "Nationally Certified Programming" },
            { iconName: "ShieldCheck", label: "No Long-Term Contracts" },
          ],
          accentColor: "#ef4444",
          textColor: "#fafafa",
          mutedColor: "#a3a3a3",
        },
        {
          type: "footer",
          brand: "Forge Athletic Co.",
          menu: [{ label: "Classes" }, { label: "Personal Training" }, { label: "Coaches" }, { label: "Membership" }],
          links: [{ provider: "instagram" }, { provider: "tiktok" }, { provider: "youtube" }],
          copyright: "© Forge Athletic Co. Train hard. Recover harder.",
          bg: "#111111",
        },
      ],
    },
    {
      name: "Vitalis Telehealth Wellness — Full Clinic Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A clean, clinical landing page for a telehealth and wellness clinic covering how virtual visits work, provider credibility, patient stories, and care plans.",
      pageStyle: { backgroundColor: "#f0f9ff", color: "#0c4a6e", htmlTitle: "Vitalis Telehealth Wellness" },
      sections: [
        {
          type: "menubar",
          brand: "Vitalis Telehealth",
          links: [{ label: "How It Works" }, { label: "Providers" }, { label: "Plans" }, { label: "FAQ" }],
          cta: { text: "Book a Visit", href: "#book" },
          bg: "#ffffff",
          textColor: "#0c4a6e",
          accentColor: "#0284c7",
        },
        {
          type: "hero",
          eyebrow: "BOARD-CERTIFIED CARE, FROM ANYWHERE",
          heading: "See a Doctor Today — No Waiting Room Required",
          subheading: "Vitalis connects you with licensed physicians and wellness specialists over secure video, usually within the hour.",
          primaryCta: { text: "Book Your Visit", href: "#book" },
          secondaryCta: { text: "How It Works", href: "#how" },
          imageSeed: "vitalis-telehealth-hero",
          imageAlt: "Doctor consulting a patient over a secure video call",
          accentColor: "#0284c7",
          textColor: "#0c4a6e",
          mutedColor: "#475569",
        },
        {
          type: "stats",
          items: [
            { value: "180,000+", label: "Visits completed" },
            { value: "< 20 min", label: "Average wait time" },
            { value: "4.8/5", label: "Patient satisfaction" },
            { value: "50 states", label: "Licensed to practice" },
          ],
          accentColor: "#0284c7",
          textColor: "#0c4a6e",
          mutedColor: "#475569",
        },
        {
          type: "iconrow",
          heading: "Care That Fits Your Life",
          items: [
            { iconName: "Stethoscope", label: "Board-Certified Physicians" },
            { iconName: "Lock", label: "HIPAA-Secure Video Visits" },
            { iconName: "Clock", label: "Same-Day Appointments" },
            { iconName: "Phone", label: "Prescriptions Sent Electronically" },
          ],
          accentColor: "#0284c7",
          textColor: "#0c4a6e",
          mutedColor: "#475569",
        },
        {
          type: "testimonials",
          heading: "Patients Trust Vitalis",
          items: [
            { quote: "I got a diagnosis and a prescription in 25 minutes without leaving my couch.", name: "Renee A.", role: "Vitalis Patient" },
            { quote: "The follow-up care for my thyroid condition has been more consistent than any in-person clinic I've used.", name: "Oliver K.", role: "Vitalis Patient" },
            { quote: "Booking a same-day visit for my daughter's fever was the easiest healthcare experience I've had.", name: "Farrah M.", role: "Vitalis Patient" },
          ],
          cardBg: "#ffffff",
          textColor: "#0c4a6e",
          mutedColor: "#475569",
        },
        {
          type: "pricing",
          heading: "Plans for Every Kind of Care",
          tiers: [
            { name: "Pay-Per-Visit", price: "$59", period: "/visit", features: ["General consultations", "No membership required", "Prescriptions when needed"], cta: { text: "Book a Visit", href: "#book" } },
            { name: "Vitalis Plus", price: "$24", period: "/mo", features: ["Unlimited messaging with providers", "Discounted visit pricing", "Annual wellness review"], cta: { text: "Join Vitalis Plus", href: "#book" }, highlighted: true },
            { name: "Family Plan", price: "$49", period: "/mo", features: ["Up to 5 family members", "Unlimited messaging", "Priority scheduling"], cta: { text: "Choose Family Plan", href: "#book" } },
          ],
          accentColor: "#0284c7",
          textColor: "#0c4a6e",
          mutedColor: "#475569",
        },
        {
          type: "footer",
          brand: "Vitalis Telehealth Wellness",
          menu: [{ label: "Providers" }, { label: "Plans" }, { label: "Privacy" }],
          links: [{ provider: "facebook" }, { provider: "x" }],
          copyright: "© Vitalis Telehealth Wellness. Licensed in all 50 states.",
          bg: "#0c4a6e",
        },
      ],
    },
    {
      name: "Class Booking Confirmation Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A quick, friendly booking-confirmation email for a gym class reservation, with class details and an easy way to manage the booking.",
      pageStyle: { backgroundColor: "#ffffff", color: "#111111", htmlTitle: "You're Booked!" },
      sections: [
        {
          type: "hero",
          heading: "You're In, Jordan — See You on the Floor",
          subheading: "Your spot in Saturday's 9:00 AM Forge Metcon class is confirmed.",
          accentColor: "#dc2626",
          textColor: "#111111",
          mutedColor: "#6b7280",
        },
        {
          type: "table",
          heading: "Booking Details",
          headers: ["Class", "Date", "Time", "Coach"],
          rows: [["Forge Metcon", "Saturday, Aug 8", "9:00 AM", "Coach Riley"]],
        },
        {
          type: "cta",
          heading: "Running Late or Need to Cancel?",
          subheading: "Give us at least 2 hours notice so we can open your spot to someone on the waitlist.",
          cta: { text: "Manage My Booking", href: "#manage" },
          bg: "#dc2626",
          textColor: "#ffffff",
          mutedColor: "#fca5a5",
        },
        {
          type: "footer",
          brand: "Forge Athletic Co.",
          copyright: "© Forge Athletic Co. Questions? Reply to this email.",
          bg: "#111111",
        },
      ],
    },
    {
      name: "Weekly Wellness Tips Newsletter",
      kind: "EMAIL",
      tier: "quick",
      description: "A warm, practical weekly newsletter from a nutrition coach delivering one theme and a few small, actionable habit swaps.",
      pageStyle: { backgroundColor: "#fff8f0", color: "#43302b", htmlTitle: "Nourish Weekly" },
      sections: [
        {
          type: "hero",
          eyebrow: "THIS WEEK'S ISSUE",
          heading: "3 Small Swaps That Actually Stick",
          subheading: "Sustainable nutrition isn't about willpower — it's about removing friction. Here's what to try this week.",
          accentColor: "#ea580c",
          textColor: "#43302b",
          mutedColor: "#78716c",
        },
        {
          type: "richtext",
          heading: "From Your Coach",
          paragraphs: [
            "Most people don't fail at nutrition because they lack discipline — they fail because the plan asks for too much change too fast. This week, pick one swap below and give it seven days before adding another.",
            "Small, boring, repeatable habits are what actually move the needle over a year. Flashy is optional. Consistent is not.",
          ],
          textColor: "#43302b",
          mutedColor: "#78716c",
        },
        {
          type: "grid",
          heading: "Try One of These This Week",
          columns: 3,
          items: [
            { iconName: "Salad", title: "Protein First", text: "Add a palm-sized protein source to breakfast before anything else hits the plate." },
            { iconName: "Leaf", title: "One Extra Veggie", text: "Add one serving of vegetables to whatever meal you eat the least mindfully." },
            { iconName: "BookOpen", title: "5-Minute Food Log", text: "Jot down meals in a notes app — no calorie counting, just awareness." },
          ],
          accentColor: "#ea580c",
          textColor: "#43302b",
          mutedColor: "#78716c",
        },
        {
          type: "footer",
          brand: "Nourish Nutrition Coaching",
          copyright: "© Nourish Nutrition Coaching. You're receiving this because you're a client or subscriber.",
          bg: "#43302b",
        },
      ],
    },
    {
      name: "Membership Renewal Reminder Email",
      kind: "EMAIL",
      tier: "premium",
      description: "A rich, rate-locking renewal-reminder email for a wellness studio combining year-in-review stats, renewal plan options, and a testimonial to nudge the renewal.",
      pageStyle: { backgroundColor: "#faf7f0", color: "#33422f", htmlTitle: "Your Still Waters Membership Renews Soon" },
      sections: [
        {
          type: "hero",
          eyebrow: "RENEWAL NOTICE",
          heading: "Your Membership Renews in 5 Days",
          subheading: "We'd love to keep practicing alongside you — here's what your renewal includes.",
          accentColor: "#a37c40",
          textColor: "#33422f",
          mutedColor: "#6b7660",
        },
        {
          type: "stats",
          items: [
            { value: "47", label: "Classes you've attended this year" },
            { value: "12", label: "Different teachers you've practiced with" },
            { value: "1", label: "Free workshop credit waiting for you" },
          ],
          accentColor: "#a37c40",
          textColor: "#33422f",
          mutedColor: "#6b7660",
        },
        {
          type: "pricing",
          heading: "Choose Your Renewal Plan",
          tiers: [
            { name: "Drop-In Flex", price: "$22", period: "/class", features: ["No commitment", "Book any class, anytime"], cta: { text: "Stay on Drop-In", href: "#renew" } },
            { name: "Unlimited Monthly", price: "$139", period: "/mo", features: ["Unlimited classes", "Member workshop discounts", "2 guest passes/month"], cta: { text: "Renew Unlimited", href: "#renew" }, highlighted: true },
            { name: "Annual Practice", price: "$1,290", period: "/yr", features: ["Unlimited classes", "2 free workshops included", "Priority retreat booking"], cta: { text: "Renew Annual", href: "#renew" } },
          ],
          accentColor: "#a37c40",
          textColor: "#33422f",
          mutedColor: "#6b7660",
        },
        {
          type: "testimonials",
          items: [{ quote: "A year ago I could barely touch my toes. Renewing for my third year now.", name: "Beatrice L.", role: "Unlimited Member" }],
          cardBg: "#f0ead9",
          textColor: "#33422f",
          mutedColor: "#6b7660",
        },
        {
          type: "cta",
          heading: "Renew Before Friday, Keep Your Current Rate",
          subheading: "Rates go up for new members next month — yours stays locked in when you renew now.",
          cta: { text: "Renew My Membership", href: "#renew" },
          bg: "#7c9473",
          textColor: "#faf7f0",
          mutedColor: "#e4ecdf",
        },
        {
          type: "footer",
          brand: "Still Waters Yoga & Wellness",
          copyright: "© Still Waters Yoga & Wellness Spa. Manage your membership anytime.",
          bg: "#33422f",
        },
      ],
    },
    {
      name: "Free Trial Class Signup Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A short, no-pressure opt-in page inviting prospects to reserve one free trial class at a gym before committing to anything.",
      pageStyle: { backgroundColor: "#0a0a0a", color: "#fafafa", htmlTitle: "Try Forge Free" },
      sections: [
        {
          type: "hero",
          eyebrow: "FIRST CLASS, ON US",
          heading: "Come See What Forge Is Really Like",
          subheading: "One free class, no pressure, no hard sell — just an honest look at how we train.",
          accentColor: "#dc2626",
          textColor: "#fafafa",
          mutedColor: "#a3a3a3",
        },
        {
          type: "form",
          heading: "Grab Your Free Class",
          subheading: "We'll follow up to confirm your spot within a day.",
          fields: [
            { kind: "text", label: "First Name", name: "firstName", placeholder: "Jordan", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
            { kind: "select", label: "Which class interests you?", name: "classInterest", options: ["Forge Metcon", "Barbell Strength", "Not sure yet"], required: true },
          ],
          submitLabel: "Reserve My Free Class",
          accentColor: "#dc2626",
          textColor: "#fafafa",
          mutedColor: "#a3a3a3",
        },
        {
          type: "footer",
          brand: "Forge Athletic Co.",
          copyright: "© Forge Athletic Co.",
          bg: "#0a0a0a",
        },
      ],
    },
    {
      name: "Free Telehealth Consultation Booking Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A trust-focused opt-in page for a telehealth clinic offering a free, no-obligation 15-minute consultation before booking a paid visit.",
      pageStyle: { backgroundColor: "#f0f9ff", color: "#0c4a6e", htmlTitle: "Book a Free Consultation" },
      sections: [
        {
          type: "hero",
          eyebrow: "NO COST, NO OBLIGATION",
          heading: "Talk to a Provider Before You Commit",
          subheading: "Book a free 15-minute consultation to see if Vitalis is the right fit for your care.",
          accentColor: "#0284c7",
          textColor: "#0c4a6e",
          mutedColor: "#475569",
        },
        {
          type: "form",
          heading: "Schedule Your Free Consultation",
          fields: [
            { kind: "text", label: "Full Name", name: "fullName", placeholder: "Jamie Rivera", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
            { kind: "select", label: "What would you like to discuss?", name: "topic", options: ["General health", "Mental health", "Nutrition & weight", "Not sure yet"], required: true },
          ],
          submitLabel: "Book My Free Consultation",
          accentColor: "#0284c7",
          textColor: "#0c4a6e",
          mutedColor: "#475569",
        },
        {
          type: "iconrow",
          items: [
            { iconName: "Lock", label: "HIPAA-Secure" },
            { iconName: "Clock", label: "15 Minutes, No Pressure" },
            { iconName: "Stethoscope", label: "Licensed Providers" },
          ],
          accentColor: "#0284c7",
          textColor: "#0c4a6e",
          mutedColor: "#475569",
        },
        {
          type: "footer",
          brand: "Vitalis Telehealth Wellness",
          copyright: "© Vitalis Telehealth Wellness.",
          bg: "#0c4a6e",
        },
      ],
    },
    {
      name: "Free 7-Day Meal Plan Download Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A simple lead-capture page offering a free 7-day meal plan and grocery list download in exchange for an email address.",
      pageStyle: { backgroundColor: "#fff8f0", color: "#43302b", htmlTitle: "Get Your Free 7-Day Meal Plan" },
      sections: [
        {
          type: "hero",
          eyebrow: "FREE DOWNLOAD",
          heading: "A 7-Day Meal Plan That Doesn't Feel Like a Diet",
          subheading: "Real meals, a simple grocery list, and macros already worked out for you — free, no strings attached.",
          imageSeed: "nourish-meal-plan-hero",
          imageAlt: "Colorful prepared meals in glass containers",
          accentColor: "#ea580c",
          textColor: "#43302b",
          mutedColor: "#78716c",
        },
        {
          type: "form",
          heading: "Send Me the Free Plan",
          fields: [
            { kind: "text", label: "First Name", name: "firstName", placeholder: "Alex", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
          ],
          submitLabel: "Get My Free Meal Plan",
          accentColor: "#ea580c",
          textColor: "#43302b",
          mutedColor: "#78716c",
        },
        {
          type: "footer",
          brand: "Nourish Nutrition Coaching",
          copyright: "© Nourish Nutrition Coaching.",
          bg: "#43302b",
        },
      ],
    },
  ],
};
