import type { CategoryBatch } from "../types";

export const localBusinessBatch: CategoryBatch = {
  category: "Local & Small Business",
  specs: [
    {
      name: "Marigold Kitchen — Menu & Hours Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A warm, appetite-driven landing page for a neighborhood restaurant or café — hero, seasonal menu highlights, and a clear call to reserve a table.",
      pageStyle: { backgroundColor: "#fff7ed", color: "#431407", htmlTitle: "Marigold Kitchen" },
      sections: [
        {
          type: "hero",
          eyebrow: "OPEN DAILY FOR BREAKFAST, LUNCH & DINNER",
          heading: "Comfort Food, Cooked Slow, Served Warm",
          subheading: "Scratch-made dishes from local farms, a wood-fired oven, and a table that's always got room for one more.",
          primaryCta: { text: "View Our Menu", href: "#menu" },
          secondaryCta: { text: "Reserve a Table", href: "#reserve" },
          imageSeed: "marigold-kitchen-hero",
          imageAlt: "Marigold Kitchen dining room with warm lighting",
          textColor: "#431407",
          mutedColor: "#92400e",
          accentColor: "#c2410c",
        },
        {
          type: "grid",
          heading: "Today's Favorites",
          columns: 3,
          items: [
            { imageSeed: "marigold-woodfired-pizza", title: "Wood-Fired Margherita", text: "San Marzano tomatoes, fresh mozzarella, basil from our rooftop garden", price: "$16" },
            { imageSeed: "marigold-braised-short-rib", title: "Braised Short Rib", text: "Slow-braised eight hours, root vegetable purée, red wine jus", price: "$26" },
            { imageSeed: "marigold-citrus-salad", title: "Citrus & Fennel Salad", text: "Blood orange, shaved fennel, pistachio, honey vinaigrette", price: "$13" },
          ],
          accentColor: "#c2410c",
          textColor: "#431407",
          mutedColor: "#92400e",
        },
        {
          type: "cta",
          heading: "Sunday Brunch Is Back",
          subheading: "Bottomless mimosas, live jazz, and our famous cinnamon roll waffle — every Sunday, 9am–2pm.",
          cta: { text: "Reserve Your Table", href: "#reserve" },
          bg: "#c2410c",
        },
        {
          type: "footer",
          brand: "Marigold Kitchen",
          menu: [{ label: "Menu" }, { label: "Reservations" }, { label: "Private Events" }],
          links: [{ provider: "instagram" }, { provider: "facebook" }],
          copyright: "© Marigold Kitchen · 214 Elm Street · Open Tue–Sun, 8am–9pm",
          bg: "#2a1607",
        },
      ],
    },
    {
      name: "GreenEdge Landscaping & Design — Service Overview Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A clean, trust-building landing page for a landscaping or lawn-care contractor — hero, core services grid, and a seasonal call to book a free estimate.",
      pageStyle: { backgroundColor: "#f4f1e8", color: "#1f2e1a", htmlTitle: "GreenEdge Landscaping & Design" },
      sections: [
        {
          type: "hero",
          eyebrow: "SERVING THE GREATER RIVERVIEW AREA",
          heading: "Landscapes That Work as Hard as You Do",
          subheading: "Lawn care, garden design, and hardscaping from a local crew that shows up on time and cleans up after itself.",
          primaryCta: { text: "Get a Free Estimate", href: "#estimate" },
          imageSeed: "greenedge-front-yard-hero",
          imageAlt: "Freshly landscaped front yard with a stone pathway",
          textColor: "#1f2e1a",
          mutedColor: "#4b5c3f",
          accentColor: "#3f6212",
        },
        {
          type: "grid",
          heading: "What We Do",
          columns: 3,
          items: [
            { iconName: "Leaf", title: "Lawn Care & Maintenance", text: "Weekly mowing, fertilization, and seasonal cleanups" },
            { iconName: "Home", title: "Garden & Landscape Design", text: "Custom planting plans built for your soil and sunlight" },
            { iconName: "Building2", title: "Hardscaping & Patios", text: "Retaining walls, walkways, and outdoor living spaces" },
          ],
          accentColor: "#3f6212",
          textColor: "#1f2e1a",
          mutedColor: "#4b5c3f",
        },
        {
          type: "cta",
          heading: "Spring Cleanups Are Booking Fast",
          subheading: "Lock in your spot before the season fills up — most crews are booked two weeks out by April.",
          cta: { text: "Request Your Free Estimate", href: "#estimate" },
          bg: "#3f6212",
          textColor: "#ffffff",
          mutedColor: "#d9e8c8",
        },
        {
          type: "footer",
          brand: "GreenEdge Landscaping & Design",
          menu: [{ label: "Services" }, { label: "Estimates" }, { label: "Reviews" }],
          links: [{ provider: "facebook" }, { provider: "instagram" }],
          copyright: "© GreenEdge Landscaping & Design · Licensed & Insured · Mon–Sat, 7am–6pm",
          bg: "#1f2e1a",
        },
      ],
    },
    {
      name: "Lush & Vine Salon & Spa — Signature Experience Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A rich, editorial-feel landing page for a boutique hair salon and day spa — navigation, a photo gallery, signature services, client testimonials, and trust signals for a full booking site.",
      pageStyle: { backgroundColor: "#fdf2f8", color: "#500724", htmlTitle: "Lush & Vine Salon & Spa" },
      sections: [
        {
          type: "menubar",
          brand: "Lush & Vine",
          links: [{ label: "Services" }, { label: "Stylists" }, { label: "Spa Menu" }, { label: "Gift Cards" }],
          cta: { text: "Book Now", href: "#book" },
          bg: "#fdf2f8",
          textColor: "#500724",
          accentColor: "#be185d",
        },
        {
          type: "hero",
          eyebrow: "BOUTIQUE SALON & DAY SPA",
          heading: "Where Every Visit Feels Like a Reset",
          subheading: "Color, cuts, and spa rituals crafted by stylists who actually listen — in a space designed to slow you down.",
          primaryCta: { text: "Book Your Appointment", href: "#book" },
          secondaryCta: { text: "Explore the Spa Menu", href: "#spa" },
          imageSeed: "lush-vine-salon-interior",
          imageAlt: "Lush & Vine salon interior with soft lighting",
          textColor: "#500724",
          mutedColor: "#9d174d",
          accentColor: "#be185d",
        },
        {
          type: "gallery",
          heading: "Inside Lush & Vine",
          images: [
            { seed: "lush-vine-styling-chairs", alt: "Styling chairs and mirror wall" },
            { seed: "lush-vine-color-bar", alt: "Color bar with natural light" },
            { seed: "lush-vine-spa-room", alt: "Private spa treatment room" },
            { seed: "lush-vine-blowout-result", alt: "Finished blowout style" },
          ],
          textColor: "#500724",
        },
        {
          type: "grid",
          heading: "Signature Services",
          columns: 3,
          items: [
            { imageSeed: "lush-vine-balayage", title: "Balayage & Color", text: "Hand-painted color tailored to your skin tone and lifestyle", price: "From $165" },
            { imageSeed: "lush-vine-facial", title: "Signature Facial", text: "60-minute custom facial with LED light therapy", price: "From $95" },
            { imageSeed: "lush-vine-massage", title: "Hot Stone Massage", text: "90 minutes of deep-tissue relief with warmed basalt stones", price: "From $120" },
          ],
          accentColor: "#be185d",
          textColor: "#500724",
          mutedColor: "#9d174d",
        },
        {
          type: "testimonials",
          heading: "What Our Clients Say",
          items: [
            { quote: "I've been to a dozen salons in this city and none of them come close. My colorist actually remembers what I like.", name: "Nadia F.", role: "Client since 2021" },
            { quote: "The hot stone massage alone is worth the drive across town. This place is a genuine escape.", name: "Marcus T.", role: "Spa Member" },
            { quote: "Booking online is effortless and they're never running late. Rare for a salon this good.", name: "Elise R.", role: "Client since 2019" },
          ],
          cardBg: "#ffffff",
          textColor: "#500724",
          mutedColor: "#9d174d",
        },
        {
          type: "iconrow",
          heading: "Why Clients Stay With Us",
          items: [
            { iconName: "Award", label: "Master Colorists on Staff" },
            { iconName: "Sparkles", label: "Clean, Cruelty-Free Products" },
            { iconName: "Calendar", label: "Easy Online Booking" },
            { iconName: "Heart", label: "Personalized Consultations" },
          ],
          accentColor: "#be185d",
          textColor: "#500724",
          mutedColor: "#9d174d",
        },
        {
          type: "stats",
          items: [
            { value: "12+", label: "Years in the neighborhood" },
            { value: "4.9★", label: "Average client rating" },
            { value: "8", label: "Stylists & estheticians" },
          ],
          accentColor: "#be185d",
          mutedColor: "#9d174d",
        },
        {
          type: "cta",
          heading: "Your Reset Is One Booking Away",
          subheading: "New clients get 15% off their first color service.",
          cta: { text: "Book Your Visit", href: "#book" },
          bg: "#be185d",
        },
        {
          type: "footer",
          brand: "Lush & Vine Salon & Spa",
          menu: [{ label: "Services" }, { label: "Gift Cards" }, { label: "Careers" }],
          links: [{ provider: "instagram" }, { provider: "tiktok" }],
          copyright: "© Lush & Vine Salon & Spa · 88 Blossom Ave · By appointment, Tue–Sat",
          bg: "#4a044e",
        },
      ],
    },
    {
      name: "Ironclad Auto Care — Full-Service Shop Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A trust-first landing page for an independent auto repair shop, combining a service menu, technician credentials, and customer testimonials to convert local searchers into booked appointments.",
      pageStyle: { backgroundColor: "#0f172a", color: "#f1f5f9", htmlTitle: "Ironclad Auto Care" },
      sections: [
        {
          type: "menubar",
          brand: "Ironclad Auto Care",
          links: [{ label: "Services" }, { label: "Financing" }, { label: "Reviews" }],
          cta: { text: "Book a Service", href: "#book" },
          bg: "#0f172a",
          textColor: "#f1f5f9",
          accentColor: "#f97316",
        },
        {
          type: "hero",
          eyebrow: "ASE-CERTIFIED TECHNICIANS",
          heading: "Honest Repairs. No Upsells. No Surprises.",
          subheading: "From brakes to check-engine lights, we diagnose it right the first time and tell you exactly what it costs before we touch a bolt.",
          primaryCta: { text: "Schedule Service", href: "#book" },
          secondaryCta: { text: "Get a Free Quote", href: "#quote" },
          imageSeed: "ironclad-shop-bay",
          imageAlt: "Auto technician working in a service bay",
          textColor: "#f1f5f9",
          mutedColor: "#94a3b8",
          accentColor: "#f97316",
        },
        {
          type: "grid",
          heading: "Most-Requested Services",
          columns: 4,
          items: [
            { iconName: "Wallet", title: "Brakes & Rotors", text: "Pads, rotors, and fluid flush", price: "From $149" },
            { iconName: "Zap", title: "Check Engine Diagnostics", text: "Full computer scan and inspection", price: "From $89" },
            { iconName: "RotateCcw", title: "Oil & Filter Change", text: "Synthetic blend, 21-point inspection", price: "From $59" },
            { iconName: "ShieldCheck", title: "Pre-Purchase Inspection", text: "Buying used? Know before you sign.", price: "From $79" },
          ],
          accentColor: "#f97316",
          textColor: "#f1f5f9",
          mutedColor: "#94a3b8",
          bg: "#1e293b",
        },
        {
          type: "stats",
          items: [
            { value: "22 yrs", label: "Serving this neighborhood" },
            { value: "4.8★", label: "Average Google rating" },
            { value: "14,000+", label: "Vehicles repaired" },
          ],
          accentColor: "#f97316",
          mutedColor: "#94a3b8",
        },
        {
          type: "testimonials",
          heading: "Drivers Trust Ironclad",
          items: [
            { quote: "Told me straight up I didn't need the repair the dealership quoted me $1,200 for. Saved me a fortune.", name: "Dave R.", role: "Customer" },
            { quote: "Same-day brake job and they even showed me the old pads. No games, just good work.", name: "Latasha M.", role: "Customer" },
            { quote: "Been coming here for a decade with three different cars. Never once felt oversold.", name: "Ben K.", role: "Customer" },
          ],
          cardBg: "#1e293b",
          textColor: "#f1f5f9",
          mutedColor: "#94a3b8",
        },
        {
          type: "iconrow",
          heading: "The Ironclad Guarantee",
          items: [
            { iconName: "ShieldCheck", label: "12-Month / 12,000-Mile Warranty" },
            { iconName: "Clock", label: "Same-Day Service Available" },
            { iconName: "Award", label: "ASE-Certified Techs" },
            { iconName: "Truck", label: "Free Local Shuttle" },
          ],
          accentColor: "#f97316",
          textColor: "#f1f5f9",
          mutedColor: "#94a3b8",
        },
        {
          type: "cta",
          heading: "Something Sound Off Under the Hood?",
          subheading: "Book a diagnostic today and we'll call you with a straight answer — no pressure.",
          cta: { text: "Schedule My Appointment", href: "#book" },
          bg: "#f97316",
          textColor: "#1c1917",
          mutedColor: "#4a2a10",
        },
        {
          type: "footer",
          brand: "Ironclad Auto Care",
          menu: [{ label: "Services" }, { label: "Financing" }, { label: "Careers" }],
          links: [{ provider: "facebook" }, { provider: "instagram" }],
          copyright: "© Ironclad Auto Care · 500 Industrial Pkwy · Mon–Sat, 7:30am–6pm",
          bg: "#0f172a",
        },
      ],
    },
    {
      name: "Reservation Confirmed Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A warm reservation-confirmation email for a restaurant or café, confirming party details and setting expectations ahead of the visit.",
      pageStyle: { backgroundColor: "#fff7ed", color: "#431407", htmlTitle: "Your Table Is Reserved" },
      sections: [
        {
          type: "hero",
          heading: "You're All Set, Priya!",
          subheading: "Your table for 4 at Marigold Kitchen is confirmed for Saturday, August 8th at 7:00 PM.",
          accentColor: "#c2410c",
          mutedColor: "#92400e",
        },
        {
          type: "table",
          heading: "Reservation Details",
          headers: ["Detail", "Info"],
          rows: [
            ["Party Size", "4 guests"],
            ["Date & Time", "Sat, Aug 8 · 7:00 PM"],
            ["Seating", "Patio (weather permitting)"],
          ],
        },
        {
          type: "cta",
          heading: "Need to Make Changes?",
          subheading: "You can modify or cancel your reservation up to two hours before your visit.",
          cta: { text: "Manage My Reservation", href: "#manage" },
          bg: "#c2410c",
        },
        {
          type: "footer",
          brand: "Marigold Kitchen",
          copyright: "© Marigold Kitchen · 214 Elm Street · Questions? Just reply to this email.",
          bg: "#2a1607",
        },
      ],
    },
    {
      name: "Spring Cleanup Special Offer Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A seasonal promotional email offering a limited-time discount on spring lawn and garden cleanups, built to fill a contractor's early-season calendar.",
      pageStyle: { backgroundColor: "#f4f1e8", color: "#1f2e1a", htmlTitle: "Spring Cleanup Special" },
      sections: [
        {
          type: "hero",
          eyebrow: "LIMITED-TIME OFFER",
          heading: "$50 Off Your Spring Cleanup",
          subheading: "Book before March 31st and we'll take $50 off any full-yard spring cleanup — mulch, edging, and all.",
          accentColor: "#3f6212",
          mutedColor: "#4b5c3f",
        },
        {
          type: "grid",
          heading: "What's Included",
          columns: 3,
          items: [
            { iconName: "Leaf", title: "Bed Cleanup", text: "Leaves, debris, and dead growth cleared" },
            { iconName: "Home", title: "Fresh Mulch", text: "Up to 3 cubic yards installed" },
            { iconName: "Sparkles", title: "Edging & Trim", text: "Clean lines along beds and walkways" },
          ],
          accentColor: "#3f6212",
          textColor: "#1f2e1a",
          mutedColor: "#4b5c3f",
        },
        {
          type: "cta",
          heading: "Offer Ends March 31",
          subheading: "Use code SPRING50 when you book.",
          cta: { text: "Claim My $50 Off", href: "#book" },
          bg: "#3f6212",
        },
        {
          type: "footer",
          brand: "GreenEdge Landscaping & Design",
          copyright: "© GreenEdge Landscaping & Design · Reply STOP to unsubscribe.",
          bg: "#1f2e1a",
        },
      ],
    },
    {
      name: "Loyalty Program Welcome Email",
      kind: "EMAIL",
      tier: "premium",
      description: "A rich welcome email for a salon or spa's loyalty program — explaining how points are earned, showcasing redeemable perks, and nudging the next booking.",
      pageStyle: { backgroundColor: "#fdf2f8", color: "#500724", htmlTitle: "Welcome to the Vine Club" },
      sections: [
        {
          type: "hero",
          eyebrow: "YOU'RE IN",
          heading: "Welcome to the Vine Club, Sam!",
          subheading: "Every visit now earns you points toward free services, product credit, and first dibs on new treatments.",
          accentColor: "#be185d",
          mutedColor: "#9d174d",
        },
        {
          type: "richtext",
          heading: "How It Works",
          paragraphs: [
            "You'll earn 1 point for every $1 spent on services and retail. Points post automatically after checkout — no card to carry, no app to open.",
            "Once you hit 250 points you can redeem them for anything from a free blowout to $50 off a color service.",
          ],
          mutedColor: "#9d174d",
        },
        {
          type: "grid",
          heading: "Redeem Your Points For",
          columns: 3,
          items: [
            { iconName: "Sparkles", title: "Free Blowout", text: "250 points" },
            { iconName: "Gift", title: "$50 Service Credit", text: "500 points" },
            { iconName: "Heart", title: "Free Signature Facial", text: "900 points" },
          ],
          accentColor: "#be185d",
        },
        {
          type: "iconrow",
          heading: "Member Perks Start Now",
          items: [
            { iconName: "Calendar", label: "Priority Booking" },
            { iconName: "Gift", label: "Birthday Reward" },
            { iconName: "Star", label: "Members-Only Events" },
          ],
          accentColor: "#be185d",
          mutedColor: "#9d174d",
        },
        {
          type: "cta",
          heading: "Your Next Visit Is Already Earning",
          subheading: "Book now and start stacking points toward your first reward.",
          cta: { text: "Book an Appointment", href: "#book" },
          bg: "#be185d",
        },
        {
          type: "footer",
          brand: "Lush & Vine Salon & Spa",
          copyright: "© Lush & Vine Salon & Spa · Manage your loyalty preferences anytime.",
          bg: "#4a044e",
        },
      ],
    },
    {
      name: "Book a Service Appointment — Auto Repair Opt-In Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A short, frictionless lead-capture page for an auto repair shop — collect a name, phone number, and issue description to schedule a callback.",
      pageStyle: { backgroundColor: "#0f172a", color: "#f1f5f9", htmlTitle: "Book a Service Appointment" },
      sections: [
        {
          type: "hero",
          eyebrow: "FREE DIAGNOSTIC CALL",
          heading: "Something Wrong With Your Car? Let's Talk.",
          subheading: "Tell us what's going on and one of our ASE-certified techs will call you back within the hour to schedule your visit.",
          accentColor: "#f97316",
          mutedColor: "#94a3b8",
        },
        {
          type: "form",
          heading: "Request a Callback",
          fields: [
            { kind: "text", label: "Full Name", name: "name", placeholder: "Jordan Lee", required: true },
            { kind: "text", label: "Phone Number", name: "phone", placeholder: "(555) 123-4567", required: true },
            { kind: "textarea", label: "What's going on with your vehicle?", name: "issue", placeholder: "e.g. grinding noise when braking", required: false },
          ],
          submitLabel: "Request My Callback",
          accentColor: "#f97316",
        },
        {
          type: "iconrow",
          items: [
            { iconName: "Clock", label: "Callback Within 1 Hour" },
            { iconName: "ShieldCheck", label: "No-Obligation Quote" },
            { iconName: "Award", label: "ASE-Certified Techs" },
          ],
          accentColor: "#f97316",
          mutedColor: "#94a3b8",
        },
        {
          type: "footer",
          brand: "Ironclad Auto Care",
          copyright: "© Ironclad Auto Care · 500 Industrial Pkwy",
          bg: "#0f172a",
        },
      ],
    },
    {
      name: "Join the Vine Club — Loyalty Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A quick opt-in page inviting salon or spa clients to join a free loyalty program and start earning points toward complimentary services.",
      pageStyle: { backgroundColor: "#fdf2f8", color: "#500724", htmlTitle: "Join the Vine Club" },
      sections: [
        {
          type: "hero",
          eyebrow: "IT'S FREE TO JOIN",
          heading: "Earn Rewards Every Time You Visit",
          subheading: "Join the Vine Club and start earning points toward free blowouts, facials, and product credit.",
          accentColor: "#be185d",
          mutedColor: "#9d174d",
        },
        {
          type: "form",
          heading: "Sign Up in 30 Seconds",
          fields: [
            { kind: "text", label: "First Name", name: "firstName", placeholder: "Sam", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
          ],
          submitLabel: "Join the Vine Club",
          accentColor: "#be185d",
        },
        {
          type: "footer",
          brand: "Lush & Vine Salon & Spa",
          copyright: "© Lush & Vine Salon & Spa",
          bg: "#4a044e",
        },
      ],
    },
    {
      name: "Get Our Seasonal Menu & Specials — Email Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A simple lead-capture page offering a downloadable seasonal menu and first access to new specials in exchange for an email signup.",
      pageStyle: { backgroundColor: "#fff7ed", color: "#431407", htmlTitle: "Get Our Seasonal Menu" },
      sections: [
        {
          type: "hero",
          eyebrow: "NEW SEASON, NEW MENU",
          heading: "Get Our Fall Menu Before Anyone Else",
          subheading: "Sign up and we'll send you our new seasonal menu, plus first access to pop-up dinners and holiday reservations.",
          imageSeed: "marigold-seasonal-spread",
          imageAlt: "Seasonal dishes spread on a wooden table",
          accentColor: "#c2410c",
          mutedColor: "#92400e",
        },
        {
          type: "form",
          heading: "Send Me the Menu",
          fields: [{ kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true }],
          submitLabel: "Get the Menu",
          accentColor: "#c2410c",
        },
        {
          type: "iconrow",
          items: [
            { iconName: "Utensils", label: "New Seasonal Dishes" },
            { iconName: "Calendar", label: "Early Reservation Access" },
            { iconName: "Gift", label: "Subscriber-Only Specials" },
          ],
          accentColor: "#c2410c",
          mutedColor: "#92400e",
        },
        {
          type: "footer",
          brand: "Marigold Kitchen",
          copyright: "© Marigold Kitchen",
          bg: "#2a1607",
        },
      ],
    },
  ],
};
