import type { CategoryBatch } from "../types";

export const musicBatch: CategoryBatch = {
  category: "Music, Artists & Podcasts",
  specs: [
    // 1. LANDING_PAGE / quick — indie band, new album
    {
      name: "Velvet Static — New Album Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A moody, image-led landing page for an indie band's new album drop, with a hero, latest-tracks grid, and a streaming call to action.",
      pageStyle: { backgroundColor: "#0c0a09", color: "#fafaf9", htmlTitle: "Velvet Static — Shadows in Amber" },
      sections: [
        {
          type: "hero",
          eyebrow: "NEW ALBUM OUT NOW",
          heading: "Shadows in Amber",
          subheading: "Eleven tracks about leaving home and not looking back — Velvet Static's most personal record yet.",
          primaryCta: { text: "Stream Now", href: "#stream" },
          secondaryCta: { text: "Watch the Video", href: "#video" },
          imageSeed: "velvet-static-album-cover",
          imageAlt: "Velvet Static — Shadows in Amber album artwork",
          textColor: "#fafaf9",
          mutedColor: "#a8a29e",
          accentColor: "#f59e0b",
        },
        {
          type: "grid",
          heading: "From the Record",
          columns: 3,
          items: [
            { imageSeed: "velvet-static-track-1", title: "Amber Light", text: "The record's slow-burning opener", cta: { text: "Listen", href: "#" } },
            { imageSeed: "velvet-static-track-2", title: "Static Hymn", text: "Lead single, out since April", cta: { text: "Listen", href: "#" } },
            { imageSeed: "velvet-static-track-3", title: "Leaving Ohio", text: "A quiet closer about going home", cta: { text: "Listen", href: "#" } },
          ],
          accentColor: "#f59e0b",
          textColor: "#fafaf9",
          mutedColor: "#a8a29e",
          bg: "#1c1917",
        },
        {
          type: "cta",
          heading: "Shadows in Amber Is Out Everywhere",
          subheading: "Stream on Spotify, Apple Music, Bandcamp, and everywhere you listen.",
          cta: { text: "Stream Now", href: "#stream" },
          bg: "#f59e0b",
          textColor: "#1c1917",
          mutedColor: "#78350f",
        },
        {
          type: "footer",
          brand: "Velvet Static",
          menu: [{ label: "Music" }, { label: "Tour" }, { label: "Merch" }],
          links: [{ provider: "instagram" }, { provider: "spotify" }, { provider: "youtube" }],
          copyright: "© Velvet Static. Shadows in Amber, out now.",
          bg: "#0c0a09",
        },
      ],
    },

    // 2. LANDING_PAGE / quick — EDM DJ, tour + latest mix
    {
      name: "Nova Pulse — Tour Dates & Latest Mix Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A high-energy neon landing page for an EDM DJ, spotlighting upcoming tour stops and the latest mix with a bold streaming CTA.",
      pageStyle: { backgroundColor: "#05010d", color: "#f5f3ff", htmlTitle: "Nova Pulse — Live Tour" },
      sections: [
        {
          type: "hero",
          eyebrow: "WORLD TOUR 2026",
          heading: "Nova Pulse Is Coming to Your City",
          subheading: "Twelve cities. One night each. The Afterglow tour drops the biggest set of the year.",
          primaryCta: { text: "See Tour Dates", href: "#tour" },
          secondaryCta: { text: "Play Latest Mix", href: "#mix" },
          imageSeed: "nova-pulse-hero",
          imageAlt: "Nova Pulse performing under neon lights",
          textColor: "#f5f3ff",
          mutedColor: "#a78bfa",
          accentColor: "#22d3ee",
        },
        {
          type: "grid",
          heading: "Upcoming Tour Dates",
          columns: 3,
          items: [
            { imageSeed: "nova-pulse-city-1", title: "Miami — Sept 12", text: "Ultra Stage, Bayfront Park", cta: { text: "Get Tickets", href: "#" } },
            { imageSeed: "nova-pulse-city-2", title: "Berlin — Sept 26", text: "Tresor Warehouse", cta: { text: "Get Tickets", href: "#" } },
            { imageSeed: "nova-pulse-city-3", title: "Tokyo — Oct 3", text: "Zero Arena", cta: { text: "Get Tickets", href: "#" } },
          ],
          accentColor: "#22d3ee",
          textColor: "#f5f3ff",
          mutedColor: "#a78bfa",
          bg: "#0f0620",
        },
        {
          type: "cta",
          heading: "Afterglow (Live Mix) Is Streaming Now",
          subheading: "90 minutes recorded live in Ibiza — turn it up.",
          cta: { text: "Stream the Mix", href: "#mix" },
          bg: "#22d3ee",
          textColor: "#05010d",
          mutedColor: "#0e4b52",
        },
        {
          type: "footer",
          brand: "Nova Pulse",
          menu: [{ label: "Tour" }, { label: "Mixes" }, { label: "Bookings" }],
          links: [{ provider: "instagram" }, { provider: "soundcloud" }, { provider: "tiktok" }],
          copyright: "© Nova Pulse. Afterglow World Tour 2026.",
          bg: "#05010d",
        },
      ],
    },

    // 3. LANDING_PAGE / premium — record label roster page
    {
      name: "Echo Room Records — Label Roster & Showcase Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A rich, full-navigation label homepage with an artist roster, showreel video, studio gallery, streaming stats, and press quotes — built for an independent record label.",
      pageStyle: { backgroundColor: "#0f0f0f", color: "#f4f4f5", htmlTitle: "Echo Room Records" },
      sections: [
        {
          type: "menubar",
          brand: "Echo Room Records",
          links: [{ label: "Artists" }, { label: "Releases" }, { label: "Demos" }, { label: "About" }],
          cta: { text: "Submit a Demo", href: "#demo" },
          bg: "#0f0f0f",
          textColor: "#f4f4f5",
          accentColor: "#eab308",
        },
        {
          type: "hero",
          eyebrow: "INDEPENDENT SINCE 2014",
          heading: "Where Unheard Sound Finds Its Room",
          subheading: "Echo Room Records signs and develops artists across indie rock, electronic, and hip-hop — no genre gatekeeping, just great records.",
          primaryCta: { text: "Meet the Roster", href: "#artists" },
          secondaryCta: { text: "Submit a Demo", href: "#demo" },
          imageSeed: "echo-room-studio-hero",
          imageAlt: "Echo Room Records studio session",
          textColor: "#f4f4f5",
          mutedColor: "#a1a1aa",
          accentColor: "#eab308",
        },
        {
          type: "video",
          heading: "Inside the Echo Room",
          subheading: "A look at how our roster writes, records, and releases.",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          alt: "Echo Room Records studio showreel",
          textColor: "#f4f4f5",
          mutedColor: "#a1a1aa",
        },
        {
          type: "grid",
          heading: "The Roster",
          columns: 4,
          items: [
            { imageSeed: "echo-room-artist-velvet-static", title: "Velvet Static", text: "Indie rock", cta: { text: "View Artist", href: "#" } },
            { imageSeed: "echo-room-artist-nova-pulse", title: "Nova Pulse", text: "Electronic / EDM", cta: { text: "View Artist", href: "#" } },
            { imageSeed: "echo-room-artist-lowlight", title: "Lowlight", text: "Bedroom pop", cta: { text: "View Artist", href: "#" } },
            { imageSeed: "echo-room-artist-brass-tacks", title: "Brass Tacks", text: "Hip-hop", cta: { text: "View Artist", href: "#" } },
          ],
          accentColor: "#eab308",
          textColor: "#f4f4f5",
          mutedColor: "#a1a1aa",
          bg: "#18181b",
        },
        {
          type: "gallery",
          heading: "From the Studio Floor",
          images: [
            { seed: "echo-room-gallery-1", alt: "Mixing console at Echo Room Studios", caption: "Studio A, mix week" },
            { seed: "echo-room-gallery-2", alt: "Live band tracking session", caption: "Velvet Static tracking Shadows in Amber" },
            { seed: "echo-room-gallery-3", alt: "Vinyl pressing plant", caption: "First pressing, 2026" },
          ],
          textColor: "#f4f4f5",
          bg: "#0f0f0f",
        },
        {
          type: "stats",
          items: [
            { value: "48M+", label: "Monthly streams across the roster" },
            { value: "22", label: "Artists signed since 2014" },
            { value: "6", label: "Charting releases this year" },
          ],
          accentColor: "#eab308",
          textColor: "#f4f4f5",
          mutedColor: "#a1a1aa",
          bg: "#18181b",
        },
        {
          type: "testimonials",
          heading: "What the Press Is Saying",
          items: [
            { quote: "Echo Room has quietly become the most reliable taste-maker label in indie music.", name: "Rolling Stone", role: "Album Review" },
            { quote: "Every Echo Room signing feels curated, never rushed. That's rare in this business.", name: "Pitchfork", role: "Label Spotlight" },
            { quote: "The roster's diversity is the whole point — and it works.", name: "The Fader", role: "Feature" },
          ],
          cardBg: "#18181b",
          textColor: "#f4f4f5",
          mutedColor: "#a1a1aa",
        },
        {
          type: "footer",
          brand: "Echo Room Records",
          menu: [{ label: "Artists" }, { label: "Releases" }, { label: "Demo Submissions" }, { label: "Contact" }],
          links: [{ provider: "instagram" }, { provider: "spotify" }, { provider: "youtube" }, { provider: "x" }],
          copyright: "© Echo Room Records. All rights reserved.",
          bg: "#0f0f0f",
        },
      ],
    },

    // 4. LANDING_PAGE / premium — true-crime podcast
    {
      name: "Midnight Docket — True Crime Podcast Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "An atmospheric, noir-toned podcast homepage with a latest-episode embed, listener stats, press testimonials, and a full episode archive grid.",
      pageStyle: { backgroundColor: "#1c1410", color: "#f5e9da", htmlTitle: "Midnight Docket — A True Crime Podcast" },
      sections: [
        {
          type: "menubar",
          brand: "Midnight Docket",
          links: [{ label: "Episodes" }, { label: "Cases" }, { label: "Merch" }, { label: "About" }],
          cta: { text: "Listen Now", href: "#listen" },
          bg: "#1c1410",
          textColor: "#f5e9da",
          accentColor: "#b45309",
        },
        {
          type: "hero",
          eyebrow: "NEW EPISODE EVERY TUESDAY",
          heading: "Every Case Has a File. We Open It.",
          subheading: "Midnight Docket investigates cold cases, courtroom transcripts, and the unanswered questions that never made the headlines.",
          primaryCta: { text: "Listen to the Latest Episode", href: "#listen" },
          secondaryCta: { text: "Browse the Case Files", href: "#cases" },
          imageSeed: "midnight-docket-hero",
          imageAlt: "Midnight Docket case file on a desk under lamplight",
          textColor: "#f5e9da",
          mutedColor: "#c2b8ab",
          accentColor: "#b45309",
        },
        {
          type: "video",
          heading: "Episode 114: The Blackwell Ledger",
          subheading: "A missing accountant, a decades-old ledger, and a family that still won't talk.",
          videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
          alt: "Midnight Docket Episode 114 video companion",
          textColor: "#f5e9da",
          mutedColor: "#c2b8ab",
        },
        {
          type: "stats",
          items: [
            { value: "3.2M", label: "Monthly listeners" },
            { value: "#4", label: "True Crime chart rank" },
            { value: "114", label: "Case files opened" },
          ],
          accentColor: "#b45309",
          textColor: "#f5e9da",
          mutedColor: "#c2b8ab",
          bg: "#241b15",
        },
        {
          type: "grid",
          heading: "Recent Case Files",
          columns: 3,
          items: [
            { imageSeed: "midnight-docket-ep-112", title: "Ep. 112: The Overlook Motel", text: "A cold case reopened after 30 years", cta: { text: "Listen", href: "#" } },
            { imageSeed: "midnight-docket-ep-113", title: "Ep. 113: The Second Witness", text: "New testimony changes everything", cta: { text: "Listen", href: "#" } },
            { imageSeed: "midnight-docket-ep-114", title: "Ep. 114: The Blackwell Ledger", text: "This week's investigation", cta: { text: "Listen", href: "#" } },
          ],
          accentColor: "#b45309",
          textColor: "#f5e9da",
          mutedColor: "#c2b8ab",
          bg: "#1c1410",
        },
        {
          type: "testimonials",
          heading: "As Heard On",
          items: [
            { quote: "Midnight Docket does the meticulous, patient reporting most true crime shows skip.", name: "The Atlantic", role: "Podcast Review" },
            { quote: "One of the few true crime shows that treats victims' families with real care.", name: "Vulture", role: "Best of 2026" },
          ],
          cardBg: "#241b15",
          textColor: "#f5e9da",
          mutedColor: "#c2b8ab",
        },
        {
          type: "footer",
          brand: "Midnight Docket",
          menu: [{ label: "All Episodes" }, { label: "Submit a Case Tip" }, { label: "Merch" }],
          links: [{ provider: "instagram" }, { provider: "spotify" }, { provider: "apple-podcasts" }],
          copyright: "© Midnight Docket Productions. New episodes every Tuesday.",
          bg: "#1c1410",
        },
      ],
    },

    // 5. EMAIL / quick — new single announcement
    {
      name: "New Single Release Announcement Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A clean release-day email announcing a new single, with a stream-now CTA and links to every major platform.",
      pageStyle: { backgroundColor: "#0c0a09", color: "#fafaf9", htmlTitle: "Static Hymn — Out Now" },
      sections: [
        {
          type: "hero",
          eyebrow: "OUT TODAY",
          heading: "Static Hymn Is Out Now",
          subheading: "The first single off Shadows in Amber is streaming everywhere — thanks for waiting on this one.",
          primaryCta: { text: "Stream Static Hymn", href: "#stream" },
          imageSeed: "velvet-static-single-cover",
          imageAlt: "Static Hymn single artwork",
          textColor: "#fafaf9",
          mutedColor: "#a8a29e",
          accentColor: "#f59e0b",
        },
        {
          type: "cta",
          heading: "Available Everywhere You Listen",
          subheading: "Spotify, Apple Music, Bandcamp, and YouTube — take your pick.",
          cta: { text: "Stream Now", href: "#stream" },
          bg: "#f59e0b",
          textColor: "#1c1917",
          mutedColor: "#78350f",
        },
        {
          type: "footer",
          brand: "Velvet Static",
          copyright: "© Velvet Static. You're on this list because you signed up at velvetstatic.com.",
          bg: "#0c0a09",
        },
      ],
    },

    // 6. EMAIL / quick — tour date announcement
    {
      name: "Tour Date Announcement Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A punchy tour-announcement email listing the first wave of dates with an urgent presale call to action.",
      pageStyle: { backgroundColor: "#05010d", color: "#f5f3ff", htmlTitle: "Afterglow Tour — Dates Announced" },
      sections: [
        {
          type: "hero",
          eyebrow: "TOUR ANNOUNCEMENT",
          heading: "The Afterglow Tour Is Official",
          subheading: "Twelve cities. Presale opens Thursday at 10am local time — general sale follows Friday.",
          primaryCta: { text: "See All Dates", href: "#tour" },
          accentColor: "#22d3ee",
          mutedColor: "#a78bfa",
        },
        {
          type: "grid",
          heading: "First Wave of Dates",
          columns: 3,
          items: [
            { title: "Miami, FL", text: "Sept 12 — Bayfront Park", cta: { text: "Presale", href: "#" } },
            { title: "Berlin, DE", text: "Sept 26 — Tresor", cta: { text: "Presale", href: "#" } },
            { title: "Tokyo, JP", text: "Oct 3 — Zero Arena", cta: { text: "Presale", href: "#" } },
          ],
          accentColor: "#22d3ee",
        },
        {
          type: "footer",
          brand: "Nova Pulse",
          copyright: "© Nova Pulse. Presale code sent separately — check your inbox.",
          bg: "#05010d",
        },
      ],
    },

    // 7. EMAIL / premium — podcast new season announcement
    {
      name: "New Podcast Season Announcement Email",
      kind: "EMAIL",
      tier: "premium",
      description: "A richly composed season-premiere email combining a release-day CTA, the new episode lineup, a listener stat callout, and press praise — built for podcast network launch sends.",
      pageStyle: { backgroundColor: "#1c1410", color: "#f5e9da", htmlTitle: "Midnight Docket — Season 6 Premieres Tonight" },
      sections: [
        {
          type: "hero",
          eyebrow: "SEASON 6 PREMIERES TONIGHT",
          heading: "The Blackwell File Opens Tonight at Midnight",
          subheading: "Six new episodes, one case, told over six weeks — our most ambitious season yet.",
          primaryCta: { text: "Listen to the Premiere", href: "#listen" },
          textColor: "#f5e9da",
          mutedColor: "#c2b8ab",
          accentColor: "#b45309",
        },
        {
          type: "table",
          heading: "Season 6 Episode Schedule",
          headers: ["Episode", "Release Date", "Title"],
          rows: [
            ["6.1", "Aug 11", "The Ledger Resurfaces"],
            ["6.2", "Aug 18", "A Family's Silence"],
            ["6.3", "Aug 25", "The Second Witness"],
          ],
        },
        {
          type: "stats",
          items: [
            { value: "3.2M", label: "Monthly listeners" },
            { value: "114", label: "Case files opened so far" },
          ],
          accentColor: "#b45309",
          mutedColor: "#c2b8ab",
        },
        {
          type: "testimonials",
          items: [
            { quote: "Midnight Docket's new season is its most patient, most devastating work yet.", name: "The Atlantic", role: "Advance Review" },
          ],
          cardBg: "#241b15",
          textColor: "#f5e9da",
          mutedColor: "#c2b8ab",
        },
        {
          type: "cta",
          heading: "Don't Miss the Premiere",
          subheading: "Episode 6.1 drops at midnight — set a reminder now.",
          cta: { text: "Listen at Midnight", href: "#listen" },
          bg: "#b45309",
          textColor: "#1c1410",
          mutedColor: "#4a2c0f",
        },
        {
          type: "footer",
          brand: "Midnight Docket",
          copyright: "© Midnight Docket Productions. Manage your email preferences anytime.",
          bg: "#1c1410",
        },
      ],
    },

    // 8. LANDING_PAGE / quick opt-in — fan club signup
    {
      name: "Fan Club Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A short, warm opt-in page inviting fans to join a band's mailing list for early access to tickets, merch, and unreleased demos.",
      pageStyle: { backgroundColor: "#0c0a09", color: "#fafaf9", htmlTitle: "Join the Static Society" },
      sections: [
        {
          type: "hero",
          eyebrow: "FAN CLUB",
          heading: "Join the Static Society",
          subheading: "First access to presale tickets, unreleased demos, and the occasional 2am voice memo from the studio.",
          accentColor: "#f59e0b",
          mutedColor: "#a8a29e",
        },
        {
          type: "form",
          heading: "Sign Up — It's Free",
          subheading: "One or two emails a month. No spam, ever.",
          fields: [
            { kind: "text", label: "First Name", name: "firstName", placeholder: "Jamie", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
          ],
          submitLabel: "Join the Society",
          accentColor: "#f59e0b",
        },
        {
          type: "footer",
          brand: "Velvet Static",
          copyright: "© Velvet Static.",
          bg: "#1c1917",
        },
      ],
    },

    // 9. LANDING_PAGE / quick opt-in — tour-date notification signup
    {
      name: "Tour Notification Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A minimal opt-in landing page letting fans register for a text and email alert the moment a tour date is announced in their city.",
      pageStyle: { backgroundColor: "#05010d", color: "#f5f3ff", htmlTitle: "Get Notified — Nova Pulse Tour" },
      sections: [
        {
          type: "hero",
          eyebrow: "TOUR ALERTS",
          heading: "Get Notified the Second Nova Pulse Announces Your City",
          subheading: "Drop your details below — we'll ping you before tickets go public.",
          accentColor: "#22d3ee",
          mutedColor: "#a78bfa",
        },
        {
          type: "form",
          heading: "Never Miss a Tour Date",
          fields: [
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
            { kind: "text", label: "City", name: "city", placeholder: "Where should we look?", required: true },
          ],
          submitLabel: "Notify Me",
          accentColor: "#22d3ee",
        },
        {
          type: "iconrow",
          items: [
            { iconName: "Mail", label: "Email alerts" },
            { iconName: "Ticket", label: "Presale access" },
            { iconName: "MapPin", label: "City-specific updates" },
          ],
          accentColor: "#22d3ee",
          textColor: "#f5f3ff",
          mutedColor: "#a78bfa",
        },
        {
          type: "footer",
          brand: "Nova Pulse",
          copyright: "© Nova Pulse.",
          bg: "#0f0620",
        },
      ],
    },

    // 10. LANDING_PAGE / quick opt-in — free bonus episode download
    {
      name: "Free Bonus Episode Download Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A focused opt-in landing page trading a free, subscriber-only bonus episode for an email address — ideal for podcast list-building.",
      pageStyle: { backgroundColor: "#1c1410", color: "#f5e9da", htmlTitle: "Midnight Docket — Free Bonus Episode" },
      sections: [
        {
          type: "hero",
          eyebrow: "SUBSCRIBERS ONLY",
          heading: "Get Our Unreleased Bonus Episode — Free",
          subheading: "\"The Case We Almost Didn't Run\" never aired publicly. Enter your email and we'll send it straight to your inbox.",
          imageSeed: "midnight-docket-bonus-episode",
          imageAlt: "Midnight Docket bonus episode cover art",
          accentColor: "#b45309",
          mutedColor: "#c2b8ab",
        },
        {
          type: "form",
          heading: "Send Me the Episode",
          fields: [{ kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true }],
          submitLabel: "Get the Bonus Episode",
          accentColor: "#b45309",
        },
        {
          type: "footer",
          brand: "Midnight Docket",
          copyright: "© Midnight Docket Productions.",
          bg: "#241b15",
        },
      ],
    },
  ],
};
