import type { CategoryBatch } from "../types";

export const realEstateBatch: CategoryBatch = {
  category: "Real Estate & Hospitality",
  specs: [
    {
      name: "The Birchwood Estate — Luxury Property Listing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A refined single-property listing page for a high-end home, pairing a striking hero image with estate highlights and a private-tour call to action.",
      pageStyle: { backgroundColor: "#faf6ee", color: "#2b2013", htmlTitle: "The Birchwood Estate" },
      sections: [
        {
          type: "hero",
          eyebrow: "NOW FOR SALE",
          heading: "The Birchwood Estate — Timeless Elegance on Five Private Acres",
          subheading: "A meticulously restored six-bedroom manor featuring vaulted ceilings, a chef's kitchen, and panoramic vineyard views.",
          primaryCta: { text: "Schedule a Private Tour", href: "#tour" },
          secondaryCta: { text: "View Floor Plans", href: "#plans" },
          imageSeed: "birchwood-estate-facade",
          imageAlt: "The Birchwood Estate manor exterior at golden hour",
          textColor: "#2b2013",
          mutedColor: "#6b5d47",
          accentColor: "#a67c1e",
        },
        {
          type: "grid",
          heading: "Estate Highlights",
          columns: 3,
          items: [
            { iconName: "Home", title: "6 Bedrooms, 7 Baths", text: "Generous suites with en-suite baths and custom millwork throughout." },
            { iconName: "Leaf", title: "5 Private Acres", text: "Manicured gardens, a vineyard row, and a spring-fed pond." },
            { iconName: "ShieldCheck", title: "Fully Restored in 2024", text: "New roof, wiring, and mechanical systems with every period detail preserved." },
          ],
          accentColor: "#a67c1e",
          textColor: "#2b2013",
          mutedColor: "#6b5d47",
        },
        {
          type: "cta",
          heading: "Ready to See It in Person?",
          subheading: "Private tours are available by appointment, seven days a week.",
          cta: { text: "Schedule a Tour", href: "#tour" },
          bg: "#2b2013",
          textColor: "#f5ecd9",
          mutedColor: "#c9b28f",
        },
        {
          type: "footer",
          brand: "The Birchwood Estate",
          menu: [{ label: "Gallery" }, { label: "Floor Plans" }, { label: "Contact Agent" }],
          links: [{ provider: "instagram" }, { provider: "facebook" }],
          copyright: "© The Birchwood Estate. Listed exclusively by Aurelie Realty Group.",
          bg: "#2b2013",
        },
      ],
    },
    {
      name: "Cove & Anchor — Oceanfront Cottage Rental Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A breezy, image-forward landing page for a vacation-rental cottage, built to turn browsers into direct bookings.",
      pageStyle: { backgroundColor: "#f0f9ff", color: "#0c4a6e", htmlTitle: "Cove & Anchor" },
      sections: [
        {
          type: "hero",
          eyebrow: "OCEANFRONT ESCAPE",
          heading: "Wake Up to the Sound of Waves",
          subheading: "A hand-restored three-bedroom cottage steps from the sand — your own stretch of coastline, all to yourselves.",
          primaryCta: { text: "Check Availability", href: "#book" },
          imageSeed: "cove-anchor-cottage-exterior",
          imageAlt: "Cove & Anchor cottage porch overlooking the ocean",
          textColor: "#0c4a6e",
          mutedColor: "#5b7a8c",
          accentColor: "#0284c7",
        },
        {
          type: "grid",
          heading: "What's Waiting for You",
          columns: 3,
          items: [
            { iconName: "Home", title: "3 Bedrooms, Sleeps 6", text: "Bright, breezy rooms with ocean views from every window." },
            { iconName: "Wifi", title: "Fully Stocked & Connected", text: "High-speed Wi-Fi, a full kitchen, and beach gear included." },
            { iconName: "MapPin", title: "200 Steps to the Beach", text: "A private boardwalk leads straight down to the shoreline." },
          ],
          accentColor: "#0284c7",
          textColor: "#0c4a6e",
          mutedColor: "#5b7a8c",
        },
        {
          type: "cta",
          heading: "Only a Few Dates Left This Season",
          subheading: "Book direct and skip the platform fees.",
          cta: { text: "Book Your Stay", href: "#book" },
          bg: "#0284c7",
          textColor: "#f0f9ff",
          mutedColor: "#d3ecfb",
        },
        {
          type: "footer",
          brand: "Cove & Anchor",
          menu: [{ label: "Availability" }, { label: "House Rules" }, { label: "Contact" }],
          links: [{ provider: "instagram" }, { provider: "facebook" }],
          copyright: "© Cove & Anchor. Book direct, stay longer.",
          bg: "#0c4a6e",
        },
      ],
    },
    {
      name: "The Hollowgreen — Boutique Hotel Experience Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A rich, multi-section boutique-hotel landing page with navigation, a photo gallery, guest stats, testimonials, and room-rate pricing — built to sell the full stay, not just a room.",
      pageStyle: { backgroundColor: "#0d1f17", color: "#f1efe4", htmlTitle: "The Hollowgreen" },
      sections: [
        {
          type: "menubar",
          brand: "The Hollowgreen",
          links: [{ label: "Rooms" }, { label: "Dining" }, { label: "Spa" }, { label: "Gallery" }],
          cta: { text: "Book Now", href: "#book" },
          bg: "#0d1f17",
          textColor: "#f1efe4",
          accentColor: "#c9a86a",
        },
        {
          type: "hero",
          eyebrow: "A QUIET LUXURY, DEEP IN THE PINES",
          heading: "Where Stillness Feels Like Indulgence",
          subheading: "Eighteen rooms tucked into old-growth forest, with a wood-fired spa, a chef's tasting menu, and nothing on the agenda but rest.",
          primaryCta: { text: "Check Availability", href: "#book" },
          secondaryCta: { text: "Explore Rooms", href: "#rooms" },
          imageSeed: "hollowgreen-lodge-exterior",
          imageAlt: "The Hollowgreen lodge nestled among tall pines",
          textColor: "#f1efe4",
          mutedColor: "#b9c4b7",
          accentColor: "#c9a86a",
        },
        {
          type: "gallery",
          heading: "A Glimpse Inside",
          images: [
            { seed: "hollowgreen-room-suite", alt: "Forest-view suite with a soaking tub" },
            { seed: "hollowgreen-spa-room", alt: "Wood-fired spa and sauna room" },
            { seed: "hollowgreen-dining-hall", alt: "Candlelit dining hall with communal table" },
            { seed: "hollowgreen-forest-trail", alt: "Private forest trail behind the lodge" },
          ],
          bg: "#0d1f17",
          textColor: "#f1efe4",
        },
        {
          type: "stats",
          items: [
            { value: "18", label: "Rooms, never more" },
            { value: "4.9/5", label: "Guest satisfaction rating" },
            { value: "12", label: "Years welcoming guests" },
          ],
          accentColor: "#c9a86a",
          textColor: "#f1efe4",
          mutedColor: "#b9c4b7",
        },
        {
          type: "testimonials",
          heading: "What Guests Are Saying",
          items: [
            { quote: "The quietest, most restorative three nights I've had in years. The spa alone is worth the trip.", name: "Renata S.", role: "Guest" },
            { quote: "Every detail considered — the tasting menu, the linens, the silence. We're already planning our return.", name: "Owen K.", role: "Guest" },
          ],
          cardBg: "#152a20",
          textColor: "#f1efe4",
          mutedColor: "#b9c4b7",
        },
        {
          type: "pricing",
          heading: "Room Rates",
          subheading: "Rates include breakfast and spa access.",
          tiers: [
            { name: "Forest View Room", price: "$310/night", features: ["Queen bed", "Private balcony", "Spa access"], cta: { text: "Book Now", href: "#book" } },
            { name: "Hollow Suite", price: "$460/night", features: ["King bed", "Wood-burning fireplace", "Spa access", "Late checkout"], cta: { text: "Book Now", href: "#book" }, highlighted: true },
            { name: "Canopy Cabin", price: "$620/night", features: ["Standalone cabin", "Private outdoor tub", "Full spa access", "In-room dining"], cta: { text: "Book Now", href: "#book" } },
          ],
          accentColor: "#c9a86a",
          textColor: "#f1efe4",
          mutedColor: "#b9c4b7",
        },
        {
          type: "cta",
          heading: "Reserve Your Escape",
          subheading: "Weekends book out weeks ahead — plan yours now.",
          cta: { text: "Check Availability", href: "#book" },
          bg: "#c9a86a",
          textColor: "#0d1f17",
          mutedColor: "#3a2f18",
        },
        {
          type: "footer",
          brand: "The Hollowgreen",
          menu: [{ label: "Rooms" }, { label: "Dining" }, { label: "Spa" }, { label: "Directions" }],
          links: [{ provider: "instagram" }, { provider: "facebook" }],
          copyright: "© The Hollowgreen. A quiet luxury retreat.",
          bg: "#0d1f17",
        },
      ],
    },
    {
      name: "Meridian Journeys — Signature Travel Packages Landing Page",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A full-funnel landing page for a travel agency, combining destination highlights, traveler stats, testimonials, and tiered package pricing into one persuasive build.",
      pageStyle: { backgroundColor: "#fff7ed", color: "#431407", htmlTitle: "Meridian Journeys" },
      sections: [
        {
          type: "menubar",
          brand: "Meridian Journeys",
          links: [{ label: "Destinations" }, { label: "Packages" }, { label: "About" }],
          cta: { text: "Plan My Trip", href: "#packages" },
          bg: "#fff7ed",
          textColor: "#431407",
          accentColor: "#ea580c",
        },
        {
          type: "hero",
          eyebrow: "SMALL-GROUP JOURNEYS, BIG HORIZONS",
          heading: "Travel Further, Worry Less",
          subheading: "Hand-planned itineraries across 32 countries — flights, stays, and local guides, all handled for you.",
          primaryCta: { text: "Browse Packages", href: "#packages" },
          imageSeed: "meridian-journeys-hero",
          imageAlt: "Travelers overlooking a mountain valley at sunrise",
          textColor: "#431407",
          mutedColor: "#92603d",
          accentColor: "#ea580c",
        },
        {
          type: "stats",
          items: [
            { value: "14,000+", label: "Travelers guided since 2013" },
            { value: "32", label: "Countries covered" },
            { value: "4.8/5", label: "Average trip rating" },
          ],
          accentColor: "#ea580c",
          textColor: "#431407",
          mutedColor: "#92603d",
        },
        {
          type: "grid",
          heading: "Popular Destinations",
          columns: 3,
          items: [
            { imageSeed: "meridian-santorini", title: "Santorini, Greece", text: "7 days of whitewashed villages and sunset sails.", price: "From $2,150" },
            { imageSeed: "meridian-kyoto", title: "Kyoto, Japan", text: "10 days of temples, gardens, and tea ceremonies.", price: "From $2,890" },
            { imageSeed: "meridian-patagonia", title: "Patagonia, Chile", text: "9 days trekking glaciers and granite peaks.", price: "From $3,240" },
          ],
          accentColor: "#ea580c",
          textColor: "#431407",
          mutedColor: "#92603d",
        },
        {
          type: "testimonials",
          heading: "Journeys Our Travelers Still Talk About",
          items: [
            { quote: "Every logistic was handled — we just showed up and had the trip of our lives.", name: "Priya & Dev M.", role: "Travelers, Kyoto" },
            { quote: "Our guide in Patagonia felt like a friend by day two. Meridian gets the details right.", name: "Colin F.", role: "Traveler, Patagonia" },
          ],
          cardBg: "#ffedd5",
          textColor: "#431407",
          mutedColor: "#92603d",
        },
        {
          type: "pricing",
          heading: "Package Tiers",
          subheading: "Every package includes flights, lodging, and a dedicated trip planner.",
          tiers: [
            { name: "Explorer", price: "$2,150", period: "per person", features: ["7-night itinerary", "3-star boutique stays", "Group of up to 12"], cta: { text: "Choose Explorer", href: "#packages" } },
            { name: "Signature", price: "$2,890", period: "per person", features: ["10-night itinerary", "4-star curated stays", "Group of up to 8", "Private local guide"], cta: { text: "Choose Signature", href: "#packages" }, highlighted: true },
            { name: "Private Journey", price: "$5,400", period: "per person", features: ["Fully custom itinerary", "5-star stays", "Private driver & guide", "24/7 concierge"], cta: { text: "Choose Private", href: "#packages" } },
          ],
          accentColor: "#ea580c",
          textColor: "#431407",
          mutedColor: "#92603d",
        },
        {
          type: "cta",
          heading: "Your Next Journey Starts With a Conversation",
          subheading: "Tell us where you're dreaming of — we'll handle the rest.",
          cta: { text: "Talk to a Trip Planner", href: "#contact" },
          bg: "#ea580c",
          textColor: "#fff7ed",
          mutedColor: "#ffe4cc",
        },
        {
          type: "footer",
          brand: "Meridian Journeys",
          menu: [{ label: "Destinations" }, { label: "Packages" }, { label: "FAQs" }],
          links: [{ provider: "instagram" }, { provider: "facebook" }, { provider: "youtube" }],
          copyright: "© Meridian Journeys. Travel further.",
          bg: "#431407",
        },
      ],
    },
    {
      name: "Cove & Anchor — Booking Confirmation Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A clean vacation-rental booking-confirmation email with reservation details and a manage-booking call to action.",
      pageStyle: { backgroundColor: "#ffffff", color: "#0c4a6e", htmlTitle: "Your Stay is Confirmed" },
      sections: [
        {
          type: "hero",
          heading: "You're All Set, Jamie!",
          subheading: "Your stay at Cove & Anchor is confirmed for August 14–18, 2026.",
          accentColor: "#0284c7",
          mutedColor: "#5b7a8c",
        },
        {
          type: "table",
          heading: "Reservation Details",
          headers: ["Detail", "Info"],
          rows: [
            ["Check-in", "Aug 14, 2026 — 3:00 PM"],
            ["Check-out", "Aug 18, 2026 — 11:00 AM"],
            ["Guests", "4"],
            ["Total Paid", "$1,240.00"],
          ],
        },
        {
          type: "cta",
          heading: "Need to Adjust Your Dates?",
          subheading: "Manage your reservation anytime before check-in.",
          cta: { text: "Manage My Booking", href: "#manage" },
          bg: "#0284c7",
          textColor: "#ffffff",
          mutedColor: "#d3ecfb",
        },
        {
          type: "footer",
          brand: "Cove & Anchor",
          copyright: "© Cove & Anchor. Questions? Reply to this email.",
          bg: "#0c4a6e",
        },
      ],
    },
    {
      name: "Aurelie Realty Group — New Listing Alert Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A timely new-listing alert email for real-estate agencies, surfacing a fresh match against a buyer's saved search with a schedule-a-tour push.",
      pageStyle: { backgroundColor: "#fffdf7", color: "#2b2013", htmlTitle: "New Listing Match: The Birchwood Estate" },
      sections: [
        {
          type: "hero",
          eyebrow: "NEW LISTING MATCH",
          heading: "A New Listing Matches Your Search",
          subheading: "The Birchwood Estate just hit the market — 6 beds, 5 acres, and vineyard views.",
          accentColor: "#a67c1e",
          mutedColor: "#6b5d47",
        },
        {
          type: "grid",
          heading: "Listing Snapshot",
          columns: 2,
          items: [
            { imageSeed: "birchwood-listing-thumb", title: "The Birchwood Estate", text: "6 bed · 7 bath · 5 acres", price: "$4,250,000", cta: { text: "View Full Listing", href: "#listing" } },
            { imageSeed: "birchwood-listing-vineyard", title: "Vineyard Row & Pond", text: "Private spring-fed pond and a working vineyard row", cta: { text: "See Photos", href: "#listing" } },
          ],
          accentColor: "#a67c1e",
          textColor: "#2b2013",
          mutedColor: "#6b5d47",
        },
        {
          type: "cta",
          heading: "Don't Wait — Similar Homes Move Fast",
          subheading: "Schedule a private tour before it's gone.",
          cta: { text: "Schedule a Tour", href: "#tour" },
          bg: "#a67c1e",
          textColor: "#2b2013",
          mutedColor: "#4d3a13",
        },
        {
          type: "footer",
          brand: "Aurelie Realty Group",
          copyright: "© Aurelie Realty Group. You're receiving this because you saved a search alert.",
          bg: "#2b2013",
        },
      ],
    },
    {
      name: "The Hollowgreen — Pre-Arrival Check-In Details Email",
      kind: "EMAIL",
      tier: "premium",
      description: "A warm, detail-rich pre-arrival email for a boutique hotel, covering reservation specifics, included amenities, and directions ahead of a guest's stay.",
      pageStyle: { backgroundColor: "#f6f4ec", color: "#152a20", htmlTitle: "Your Stay at The Hollowgreen" },
      sections: [
        {
          type: "hero",
          eyebrow: "YOUR STAY IS CONFIRMED",
          heading: "We Can't Wait to Welcome You, Renata",
          subheading: "Your stay at The Hollowgreen begins September 3rd. Here's everything you need before you arrive.",
          accentColor: "#145c3a",
          mutedColor: "#5b6b60",
        },
        {
          type: "table",
          heading: "Your Reservation",
          headers: ["Detail", "Info"],
          rows: [
            ["Room", "Hollow Suite"],
            ["Check-in", "Sep 3, 2026 — 4:00 PM"],
            ["Check-out", "Sep 6, 2026 — 11:00 AM"],
            ["Spa Access", "Included daily, 7 AM–9 PM"],
          ],
        },
        {
          type: "iconrow",
          heading: "What's Included in Your Stay",
          items: [
            { iconName: "Utensils", label: "Breakfast Included" },
            { iconName: "Leaf", label: "Wood-Fired Spa Access" },
            { iconName: "Wifi", label: "Complimentary Wi-Fi" },
            { iconName: "Coffee", label: "In-Room Coffee Service" },
          ],
          accentColor: "#145c3a",
          textColor: "#152a20",
          mutedColor: "#5b6b60",
        },
        {
          type: "richtext",
          heading: "Getting Here & Getting Settled",
          paragraphs: [
            "The Hollowgreen sits twenty minutes north of the county airport, down a quiet forest road — we recommend arriving before sunset to enjoy the drive in. Parking is complimentary and just steps from the main lodge.",
            "If you have any dietary preferences for our tasting menu or would like to pre-book a spa treatment, simply reply to this email and our concierge team will take care of it before you arrive.",
          ],
          mutedColor: "#5b6b60",
        },
        {
          type: "cta",
          heading: "Questions Before You Arrive?",
          subheading: "Our concierge team is here to help.",
          cta: { text: "Contact Concierge", href: "#contact" },
          bg: "#145c3a",
          textColor: "#f1efe4",
          mutedColor: "#c7d6cc",
        },
        {
          type: "footer",
          brand: "The Hollowgreen",
          copyright: "© The Hollowgreen. See you soon.",
          bg: "#152a20",
        },
      ],
    },
    {
      name: "Aurelie Realty Group — Schedule a Private Tour Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A short, focused opt-in page for buyers to request a private property tour, collecting contact details and a preferred visiting time.",
      pageStyle: { backgroundColor: "#fffdf7", color: "#2b2013", htmlTitle: "Schedule a Private Tour" },
      sections: [
        {
          type: "hero",
          eyebrow: "PRIVATE TOURS AVAILABLE",
          heading: "See Your Next Home in Person",
          subheading: "Tell us a bit about what you're looking for, and one of our agents will set up a private tour within 24 hours.",
          accentColor: "#a67c1e",
          mutedColor: "#6b5d47",
        },
        {
          type: "form",
          heading: "Request a Private Tour",
          fields: [
            { kind: "text", label: "Full Name", name: "fullName", placeholder: "Jane Whitfield", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
            { kind: "text", label: "Phone Number", name: "phone", placeholder: "(555) 012-3456" },
            { kind: "select", label: "Preferred Time", name: "preferredTime", options: ["Morning", "Afternoon", "Evening"], required: true },
          ],
          submitLabel: "Request My Tour",
          accentColor: "#a67c1e",
        },
        {
          type: "footer",
          brand: "Aurelie Realty Group",
          copyright: "© Aurelie Realty Group.",
          bg: "#2b2013",
        },
      ],
    },
    {
      name: "Meridian Journeys — Exclusive Early-Booking Rate Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A members-only opt-in page offering travelers early access to next season's package rates before public release.",
      pageStyle: { backgroundColor: "#fff7ed", color: "#431407", htmlTitle: "Unlock Early-Booking Rates" },
      sections: [
        {
          type: "hero",
          eyebrow: "MEMBERS-ONLY PRICING",
          heading: "Get First Access to Next Season's Rates",
          subheading: "Join our early-booking list and lock in this year's prices on next year's packages — before they go public.",
          accentColor: "#ea580c",
          mutedColor: "#92603d",
        },
        {
          type: "form",
          heading: "Join the Early-Booking List",
          subheading: "We'll email you the moment rates open — no spam, ever.",
          fields: [
            { kind: "text", label: "Full Name", name: "fullName", placeholder: "Alex Rivera", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
          ],
          submitLabel: "Notify Me First",
          accentColor: "#ea580c",
        },
        {
          type: "iconrow",
          items: [
            { iconName: "Lock", label: "Rates locked before public release" },
            { iconName: "Globe", label: "Access to 32 destinations" },
            { iconName: "ShieldCheck", label: "No spam, unsubscribe anytime" },
          ],
          accentColor: "#ea580c",
          textColor: "#431407",
          mutedColor: "#92603d",
        },
        {
          type: "footer",
          brand: "Meridian Journeys",
          copyright: "© Meridian Journeys.",
          bg: "#431407",
        },
      ],
    },
    {
      name: "Aurelie Realty Group — New Listing Alerts Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A minimal opt-in page letting home buyers set their search criteria and get emailed the instant a matching property comes on the market.",
      pageStyle: { backgroundColor: "#fffdf7", color: "#2b2013", htmlTitle: "Get New Listing Alerts" },
      sections: [
        {
          type: "hero",
          eyebrow: "BE THE FIRST TO KNOW",
          heading: "Get New Listings Before They Hit the Market",
          subheading: "Set your criteria once and we'll email you the moment a matching home comes available — often before it's publicly listed.",
          accentColor: "#a67c1e",
          mutedColor: "#6b5d47",
        },
        {
          type: "form",
          heading: "Set Up Your Listing Alert",
          fields: [
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
            { kind: "select", label: "Neighborhood", name: "neighborhood", options: ["Downtown", "Hillside", "Vineyard Estates", "Waterfront"], required: true },
            { kind: "select", label: "Price Range", name: "priceRange", options: ["Under $1M", "$1M–$2.5M", "$2.5M–$5M", "$5M+"], required: true },
          ],
          submitLabel: "Start My Alert",
          accentColor: "#a67c1e",
        },
        {
          type: "footer",
          brand: "Aurelie Realty Group",
          copyright: "© Aurelie Realty Group.",
          bg: "#2b2013",
        },
      ],
    },
  ],
};
