import type { CategoryBatch } from "../types";

export const saasBatch: CategoryBatch = {
  category: "SaaS & Technology",
  specs: [
    // 1. LANDING_PAGE / quick — dev tool marketing page
    {
      name: "Nimbus API — Developer Platform Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A terminal-inspired landing page for a developer-first API platform, pairing a bold hero with a feature grid and a free-trial CTA.",
      pageStyle: { backgroundColor: "#0a0f0d", color: "#d1fae5", htmlTitle: "Nimbus API" },
      sections: [
        {
          type: "hero",
          eyebrow: "BUILT FOR DEVELOPERS",
          heading: "One API. Every Integration You'll Ever Need.",
          subheading: "Nimbus unifies 200+ third-party services behind a single, versioned API — ship integrations in hours, not sprints.",
          primaryCta: { text: "Start Free Trial", href: "#signup" },
          secondaryCta: { text: "Read the Docs", href: "#docs" },
          imageSeed: "nimbus-api-console-hero",
          imageAlt: "Nimbus API console showing live request logs",
          textColor: "#e2fbe8",
          mutedColor: "#7fb89a",
          accentColor: "#22c55e",
        },
        {
          type: "grid",
          heading: "Everything Your Team Needs to Ship",
          columns: 3,
          items: [
            { iconName: "Zap", title: "Sub-50ms Response Times", text: "A global edge network keeps every request fast, no matter where your users are." },
            { iconName: "Lock", title: "SOC 2 Type II Certified", text: "Enterprise-grade security and full audit logging, out of the box." },
            { iconName: "Wifi", title: "Real-Time Webhooks", text: "Get notified the instant data changes — no polling loops required." },
          ],
          accentColor: "#22c55e",
          textColor: "#e2fbe8",
          mutedColor: "#7fb89a",
        },
        {
          type: "cta",
          heading: "Start Building in Minutes",
          subheading: "The free tier includes 10,000 requests/month — no credit card required.",
          cta: { text: "Get Your API Key", href: "#signup" },
          bg: "#022c22",
          textColor: "#e2fbe8",
          mutedColor: "#7fb89a",
        },
        {
          type: "footer",
          brand: "Nimbus API",
          menu: [{ label: "Docs" }, { label: "Status" }, { label: "Pricing" }],
          links: [{ provider: "github" }, { provider: "x" }, { provider: "discord" }],
          copyright: "© Nimbus API, Inc. Ship faster.",
          bg: "#020805",
          textColor: "#7fb89a",
        },
      ],
    },

    // 2. LANDING_PAGE / quick — consumer productivity/finance mobile app
    {
      name: "Pocketly — Budgeting App Landing Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A warm, friendly landing page for a personal-finance mobile app, built around a hero, a feature grid, and a download CTA.",
      pageStyle: { backgroundColor: "#fff8f2", color: "#3f2a1c", htmlTitle: "Pocketly" },
      sections: [
        {
          type: "hero",
          eyebrow: "MONEY, MADE SIMPLE",
          heading: "Finally Feel Good About Your Money",
          subheading: "Pocketly tracks your spending, spots subscriptions you forgot about, and nudges you toward your savings goals — automatically.",
          primaryCta: { text: "Download Free", href: "#download" },
          imageSeed: "pocketly-app-dashboard",
          imageAlt: "Pocketly app dashboard showing spending categories",
          textColor: "#3f2a1c",
          mutedColor: "#8a6f5c",
          accentColor: "#f97316",
        },
        {
          type: "grid",
          heading: "Everything You Need to Feel in Control",
          columns: 3,
          items: [
            { iconName: "Wallet", title: "Auto-Categorized Spending", text: "See where every dollar goes without lifting a finger." },
            { iconName: "Target", title: "Smart Savings Goals", text: "Set a goal and Pocketly finds small, painless ways to hit it." },
            { iconName: "ShieldCheck", title: "Bank-Level Security", text: "256-bit encryption keeps your accounts private and protected." },
          ],
          accentColor: "#f97316",
          textColor: "#3f2a1c",
          mutedColor: "#8a6f5c",
        },
        {
          type: "cta",
          heading: "Join 2 Million People Budgeting Smarter",
          subheading: "Free to download. No hidden fees, ever.",
          cta: { text: "Get Pocketly Free", href: "#download" },
          bg: "#f97316",
          textColor: "#fff8f2",
          mutedColor: "#ffe4cc",
        },
        {
          type: "footer",
          brand: "Pocketly",
          menu: [{ label: "Features" }, { label: "Security" }, { label: "Support" }],
          links: [{ provider: "instagram" }, { provider: "tiktok" }],
          copyright: "© Pocketly, Inc. Your money, on your terms.",
          bg: "#3f2a1c",
          textColor: "#f2d9c4",
        },
      ],
    },

    // 3. LANDING_PAGE / premium — AI product marketing site
    {
      name: "Lucid AI — Writing Assistant Marketing Site",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A rich, dark-mode marketing site for an AI writing assistant — navigation, social proof stats, testimonials, and a full three-tier pricing table.",
      pageStyle: { backgroundColor: "#0f0a1e", color: "#ede9fe", htmlTitle: "Lucid AI" },
      sections: [
        {
          type: "menubar",
          brand: "Lucid AI",
          links: [{ label: "Product" }, { label: "Templates" }, { label: "Pricing" }],
          cta: { text: "Try Lucid Free", href: "#signup" },
          bg: "#0f0a1e",
          textColor: "#ede9fe",
          accentColor: "#a78bfa",
        },
        {
          type: "hero",
          eyebrow: "WRITE AT THE SPEED OF THOUGHT",
          heading: "Your AI Co-Writer for Everything You Ship",
          subheading: "Lucid drafts emails, blog posts, and product copy in your brand voice — then gets out of your way so you can just edit and send.",
          primaryCta: { text: "Try Lucid Free", href: "#signup" },
          secondaryCta: { text: "Watch Demo", href: "#demo" },
          imageSeed: "lucid-ai-editor-hero",
          imageAlt: "Lucid AI writing editor with suggestions panel",
          textColor: "#ede9fe",
          mutedColor: "#a596c9",
          accentColor: "#a78bfa",
        },
        {
          type: "stats",
          items: [
            { value: "3.2M+", label: "Documents drafted" },
            { value: "68%", label: "Average time saved" },
            { value: "40,000+", label: "Teams onboard" },
          ],
          bg: "#150f28",
          accentColor: "#c4b5fd",
          mutedColor: "#a596c9",
        },
        {
          type: "testimonials",
          heading: "Loved by Writers and Marketers Alike",
          items: [
            { quote: "Lucid cut our content production time in half without sounding like a robot wrote it.", name: "Maya Chen", role: "Head of Content, Brightloop" },
            { quote: "It actually learns our tone. First AI tool that didn't need constant re-editing.", name: "Devon Whitfield", role: "Marketing Lead, Fernwell" },
            { quote: "My team ships twice as much copy per sprint now. Genuinely changed our workflow.", name: "Priya Raman", role: "Founder, Studio Arc" },
          ],
          bg: "#0f0a1e",
          cardBg: "#1c1436",
          textColor: "#ede9fe",
          mutedColor: "#a596c9",
        },
        {
          type: "pricing",
          heading: "Plans for Every Kind of Writer",
          subheading: "Start free. Upgrade whenever you need more drafts.",
          tiers: [
            { name: "Starter", price: "$0", period: "forever", features: ["10 AI drafts / month", "Core templates", "Browser extension"], cta: { text: "Start Free", href: "#signup" } },
            { name: "Pro", price: "$24", period: "per month", features: ["Unlimited AI drafts", "Brand voice training", "Priority generation speed", "Team sharing"], cta: { text: "Start Pro Trial", href: "#signup" }, highlighted: true },
            { name: "Enterprise", price: "Custom", period: "billed annually", features: ["SSO & SCIM", "Dedicated success manager", "Custom model fine-tuning", "SLA & audit logs"], cta: { text: "Contact Sales", href: "#contact" } },
          ],
          bg: "#150f28",
          textColor: "#ede9fe",
          mutedColor: "#a596c9",
          accentColor: "#a78bfa",
        },
        {
          type: "cta",
          heading: "Stop Staring at a Blank Page",
          subheading: "Join 40,000+ teams already writing faster with Lucid.",
          cta: { text: "Try Lucid Free", href: "#signup" },
          bg: "#7c3aed",
          textColor: "#f5f3ff",
          mutedColor: "#e0d4fb",
        },
        {
          type: "footer",
          brand: "Lucid AI",
          menu: [{ label: "Product" }, { label: "Pricing" }, { label: "Careers" }, { label: "Trust Center" }],
          links: [{ provider: "x" }, { provider: "linkedin" }, { provider: "youtube" }],
          copyright: "© Lucid AI, Inc. All rights reserved.",
          bg: "#0a0716",
          textColor: "#a596c9",
        },
      ],
    },

    // 4. LANDING_PAGE / premium — project management / productivity marketing site
    {
      name: "Flowstate — Team Productivity Platform Marketing Site",
      kind: "LANDING_PAGE",
      tier: "premium",
      description: "A polished, full-funnel marketing site for a project-management platform — navigation, feature grid, stats, testimonials, integrations, and a three-tier pricing table.",
      pageStyle: { backgroundColor: "#f8fafc", color: "#0f172a", htmlTitle: "Flowstate" },
      sections: [
        {
          type: "menubar",
          brand: "Flowstate",
          links: [{ label: "Product" }, { label: "Integrations" }, { label: "Pricing" }, { label: "Customers" }],
          cta: { text: "Start Free Trial", href: "#signup" },
          bg: "#ffffff",
          textColor: "#0f172a",
          accentColor: "#2563eb",
        },
        {
          type: "hero",
          eyebrow: "PROJECT MANAGEMENT, SIMPLIFIED",
          heading: "The Calm Way to Run Your Team's Work",
          subheading: "Flowstate brings tasks, docs, and timelines into one clean workspace — so your team spends less time in status meetings and more time shipping.",
          primaryCta: { text: "Start Free Trial", href: "#signup" },
          secondaryCta: { text: "See It In Action", href: "#demo" },
          imageSeed: "flowstate-board-hero",
          imageAlt: "Flowstate project board with tasks and timeline",
          textColor: "#0f172a",
          mutedColor: "#64748b",
          accentColor: "#2563eb",
        },
        {
          type: "grid",
          heading: "Built for How Teams Actually Work",
          columns: 3,
          items: [
            { iconName: "Target", title: "Goal-Linked Tasks", text: "Every task rolls up to a team goal, so priorities are never a mystery." },
            { iconName: "Clock", title: "Automatic Timelines", text: "Deadlines shift intelligently when a dependency slips — no manual re-scheduling." },
            { iconName: "Users", title: "Built-In Collaboration", text: "Comment, mention, and share docs without leaving your task view." },
          ],
          accentColor: "#2563eb",
          textColor: "#0f172a",
          mutedColor: "#64748b",
        },
        {
          type: "stats",
          items: [
            { value: "99.98%", label: "Platform uptime" },
            { value: "1.4M+", label: "Tasks completed weekly" },
            { value: "18,000+", label: "Teams onboard" },
            { value: "4.8/5", label: "Average customer rating" },
          ],
          bg: "#eff6ff",
          accentColor: "#2563eb",
          mutedColor: "#475569",
        },
        {
          type: "testimonials",
          heading: "Teams Ship Faster With Flowstate",
          items: [
            { quote: "We cut our weekly status meeting from an hour to fifteen minutes. Flowstate just shows us where things stand.", name: "Rachel Osei", role: "COO, Brightline Studio" },
            { quote: "Switched from three different tools to just Flowstate. Onboarding took a single afternoon.", name: "Tomás Ferreira", role: "Engineering Manager, Kite Labs" },
          ],
          bg: "#ffffff",
          cardBg: "#f8fafc",
          textColor: "#0f172a",
          mutedColor: "#64748b",
        },
        {
          type: "iconrow",
          heading: "Works With the Tools You Already Use",
          items: [
            { iconName: "Mail", label: "Gmail & Outlook" },
            { iconName: "MessageCircle", label: "Slack" },
            { iconName: "FileText", label: "Google Drive" },
            { iconName: "Lock", label: "SSO / SAML" },
          ],
          accentColor: "#2563eb",
          textColor: "#0f172a",
          mutedColor: "#64748b",
        },
        {
          type: "pricing",
          heading: "Simple Pricing, No Surprises",
          subheading: "Every plan includes unlimited projects.",
          tiers: [
            { name: "Starter", price: "$0", period: "forever", features: ["Up to 5 members", "Basic timelines", "Community support"], cta: { text: "Start Free", href: "#signup" } },
            { name: "Pro", price: "$14", period: "per user / month", features: ["Unlimited members", "Automatic timelines", "Integrations", "Priority support"], cta: { text: "Start Free Trial", href: "#signup" }, highlighted: true },
            { name: "Enterprise", price: "Custom", period: "billed annually", features: ["SSO & SCIM", "Advanced permissions", "Dedicated onboarding", "99.99% SLA"], cta: { text: "Talk to Sales", href: "#contact" } },
          ],
          bg: "#eff6ff",
          textColor: "#0f172a",
          mutedColor: "#475569",
          accentColor: "#2563eb",
        },
        {
          type: "cta",
          heading: "Bring Calm to Your Team's Workweek",
          subheading: "Free for teams of up to 5. No credit card required.",
          cta: { text: "Start Free Trial", href: "#signup" },
          bg: "#2563eb",
          textColor: "#eff6ff",
          mutedColor: "#c7ddfd",
        },
        {
          type: "footer",
          brand: "Flowstate",
          menu: [{ label: "Product" }, { label: "Pricing" }, { label: "Blog" }, { label: "Careers" }],
          links: [{ provider: "x" }, { provider: "linkedin" }, { provider: "youtube" }],
          copyright: "© Flowstate, Inc. All rights reserved.",
          bg: "#0f172a",
          textColor: "#94a3b8",
        },
      ],
    },

    // 5. EMAIL / quick — dev tool welcome/onboarding email
    {
      name: "Nimbus API — Welcome & Quickstart Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A developer-friendly onboarding email that hands new signups their API key context and a three-step quickstart path.",
      pageStyle: { backgroundColor: "#0a0f0d", color: "#d1fae5", htmlTitle: "Welcome to Nimbus API" },
      sections: [
        {
          type: "hero",
          eyebrow: "YOU'RE IN",
          heading: "Welcome to Nimbus, Let's Get You Shipping",
          subheading: "Your account is live. Here's the fastest path from zero to your first successful API call.",
          primaryCta: { text: "View Your API Key", href: "#dashboard" },
          textColor: "#e2fbe8",
          mutedColor: "#7fb89a",
          accentColor: "#22c55e",
        },
        {
          type: "grid",
          heading: "Your 3-Step Quickstart",
          columns: 3,
          items: [
            { iconName: "Zap", title: "1. Grab Your Key", text: "Copy your test API key from the dashboard — it's ready now." },
            { iconName: "FileText", title: "2. Make a Call", text: "Paste our curl example into your terminal and see a live response." },
            { iconName: "Wifi", title: "3. Add a Webhook", text: "Subscribe to events so your app reacts to data in real time." },
          ],
          accentColor: "#22c55e",
          textColor: "#e2fbe8",
          mutedColor: "#7fb89a",
        },
        {
          type: "cta",
          heading: "Questions? We're in Discord.",
          subheading: "Our engineers answer integration questions there daily.",
          cta: { text: "Join the Discord", href: "#discord" },
          bg: "#022c22",
          textColor: "#e2fbe8",
          mutedColor: "#7fb89a",
        },
        {
          type: "footer",
          brand: "Nimbus API",
          copyright: "© Nimbus API, Inc. You're receiving this because you created an account.",
          bg: "#020805",
          textColor: "#7fb89a",
        },
      ],
    },

    // 6. EMAIL / quick — product update / changelog email
    {
      name: "Flowstate — Product Update & Changelog Email",
      kind: "EMAIL",
      tier: "quick",
      description: "A crisp changelog email announcing new Flowstate features, formatted for a monthly product-update newsletter.",
      pageStyle: { backgroundColor: "#f8fafc", color: "#0f172a", htmlTitle: "What's New in Flowstate" },
      sections: [
        {
          type: "hero",
          eyebrow: "AUGUST PRODUCT UPDATE",
          heading: "Three Things We Shipped This Month",
          subheading: "Faster boards, smarter automations, and a feature our customers have been asking for since launch.",
          accentColor: "#2563eb",
          mutedColor: "#64748b",
        },
        {
          type: "grid",
          heading: "What's New",
          columns: 3,
          items: [
            { iconName: "Zap", title: "Board Load Times, 3x Faster", text: "Large boards with 1,000+ tasks now render instantly." },
            { iconName: "Clock", title: "Recurring Task Automations", text: "Set a task to repeat weekly, monthly, or on any custom cadence." },
            { iconName: "Users", title: "Guest Access for Clients", text: "Invite clients to a single board without giving full workspace access." },
          ],
          accentColor: "#2563eb",
          textColor: "#0f172a",
          mutedColor: "#64748b",
        },
        {
          type: "cta",
          heading: "See the Full Changelog",
          subheading: "Every fix and improvement, documented.",
          cta: { text: "Read the Changelog", href: "#changelog" },
          bg: "#2563eb",
          textColor: "#eff6ff",
          mutedColor: "#c7ddfd",
        },
        {
          type: "footer",
          brand: "Flowstate",
          copyright: "© Flowstate, Inc. Manage your email preferences anytime.",
          bg: "#0f172a",
          textColor: "#94a3b8",
        },
      ],
    },

    // 7. EMAIL / premium — trial-ending upgrade reminder
    {
      name: "Lucid AI — Trial Ending Upgrade Reminder Email",
      kind: "EMAIL",
      tier: "premium",
      description: "A conversion-focused trial-expiration email that recaps a customer's usage, shows social proof, and lays out the pricing tiers to drive an upgrade.",
      pageStyle: { backgroundColor: "#0f0a1e", color: "#ede9fe", htmlTitle: "Your Lucid AI Trial Ends Soon" },
      sections: [
        {
          type: "hero",
          eyebrow: "3 DAYS LEFT",
          heading: "Your Free Trial Ends Soon — Keep the Momentum Going",
          subheading: "You've written some great drafts this week. Upgrade now so nothing gets interrupted.",
          primaryCta: { text: "Upgrade to Pro", href: "#upgrade" },
          textColor: "#ede9fe",
          mutedColor: "#a596c9",
          accentColor: "#a78bfa",
        },
        {
          type: "stats",
          items: [
            { value: "27", label: "Drafts generated this trial" },
            { value: "9.5 hrs", label: "Estimated time saved" },
            { value: "4", label: "Brand voice profiles trained" },
          ],
          bg: "#150f28",
          accentColor: "#c4b5fd",
          mutedColor: "#a596c9",
        },
        {
          type: "pricing",
          heading: "Pick the Plan That Fits Your Workflow",
          tiers: [
            { name: "Starter", price: "$0", period: "forever", features: ["10 AI drafts / month", "Core templates"], cta: { text: "Stay on Starter", href: "#downgrade" } },
            { name: "Pro", price: "$24", period: "per month", features: ["Unlimited AI drafts", "Brand voice training", "Priority generation speed"], cta: { text: "Upgrade to Pro", href: "#upgrade" }, highlighted: true },
            { name: "Enterprise", price: "Custom", period: "billed annually", features: ["SSO & SCIM", "Dedicated success manager"], cta: { text: "Contact Sales", href: "#contact" } },
          ],
          bg: "#0f0a1e",
          textColor: "#ede9fe",
          mutedColor: "#a596c9",
          accentColor: "#a78bfa",
        },
        {
          type: "testimonials",
          items: [
            { quote: "Upgrading paid for itself in the first week. I don't know how I wrote without it.", name: "Isabel Cortez", role: "Content Lead, Northwind Studio" },
          ],
          bg: "#150f28",
          cardBg: "#1c1436",
          textColor: "#ede9fe",
          mutedColor: "#a596c9",
        },
        {
          type: "cta",
          heading: "Don't Lose Your Trained Brand Voice",
          subheading: "Upgrade before your trial ends to keep everything you've set up.",
          cta: { text: "Upgrade to Pro", href: "#upgrade" },
          bg: "#7c3aed",
          textColor: "#f5f3ff",
          mutedColor: "#e0d4fb",
        },
        {
          type: "footer",
          brand: "Lucid AI",
          copyright: "© Lucid AI, Inc. You're receiving this because your trial is ending.",
          bg: "#0a0716",
          textColor: "#a596c9",
        },
      ],
    },

    // 8. LANDING_PAGE / opt-in / quick — free trial signup (consumer app)
    {
      name: "Pocketly — Free Trial Signup Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A short, friendly opt-in page for starting a free Pocketly Premium trial, built around a hero and a single-step signup form.",
      pageStyle: { backgroundColor: "#fff8f2", color: "#3f2a1c", htmlTitle: "Start Your Free Pocketly Trial" },
      sections: [
        {
          type: "hero",
          eyebrow: "14 DAYS FREE",
          heading: "Try Pocketly Premium, On Us",
          subheading: "Unlock unlimited budgets, bill negotiation, and net-worth tracking — free for two weeks, no card required.",
          accentColor: "#f97316",
          mutedColor: "#8a6f5c",
        },
        {
          type: "form",
          heading: "Start Your Free Trial",
          subheading: "Takes less than a minute to set up.",
          fields: [
            { kind: "text", label: "First Name", name: "firstName", placeholder: "Jordan", required: true },
            { kind: "email", label: "Email Address", name: "email", placeholder: "you@example.com", required: true },
          ],
          submitLabel: "Start My Free Trial",
          accentColor: "#f97316",
        },
        {
          type: "iconrow",
          items: [
            { iconName: "ShieldCheck", label: "Bank-level security" },
            { iconName: "Wallet", label: "No card required" },
            { iconName: "ThumbsUp", label: "Cancel anytime" },
          ],
          accentColor: "#f97316",
          textColor: "#3f2a1c",
          mutedColor: "#8a6f5c",
        },
        {
          type: "footer",
          brand: "Pocketly",
          copyright: "© Pocketly, Inc.",
          bg: "#3f2a1c",
          textColor: "#f2d9c4",
        },
      ],
    },

    // 9. LANDING_PAGE / opt-in / quick — waitlist / early access signup
    {
      name: "Flowstate — Early Access Waitlist Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A minimal waitlist page for an upcoming Flowstate feature, collecting emails ahead of a limited early-access rollout.",
      pageStyle: { backgroundColor: "#eff6ff", color: "#0f172a", htmlTitle: "Flowstate Early Access" },
      sections: [
        {
          type: "hero",
          eyebrow: "COMING SOON",
          heading: "Be First to Try Flowstate AI Summaries",
          subheading: "Get a daily digest of what changed across every project — automatically written, always accurate. Early access starts next month.",
          accentColor: "#2563eb",
          mutedColor: "#475569",
        },
        {
          type: "form",
          heading: "Join the Waitlist",
          subheading: "We're letting in a small batch of teams each week.",
          fields: [{ kind: "email", label: "Work Email Address", name: "email", placeholder: "you@company.com", required: true }],
          submitLabel: "Join the Waitlist",
          accentColor: "#2563eb",
        },
        {
          type: "footer",
          brand: "Flowstate",
          copyright: "© Flowstate, Inc.",
          bg: "#0f172a",
          textColor: "#94a3b8",
        },
      ],
    },

    // 10. LANDING_PAGE / opt-in / quick — demo request page
    {
      name: "Lucid AI — Enterprise Demo Request Page",
      kind: "LANDING_PAGE",
      tier: "quick",
      description: "A focused demo-request landing page for enterprise buyers evaluating Lucid AI, pairing a value-driven hero with a short qualifying form.",
      pageStyle: { backgroundColor: "#0f0a1e", color: "#ede9fe", htmlTitle: "Request a Lucid AI Demo" },
      sections: [
        {
          type: "hero",
          eyebrow: "FOR TEAMS OF 20+",
          heading: "See How Lucid AI Fits Your Content Workflow",
          subheading: "Book a 20-minute walkthrough with our team — we'll show you brand voice training, team controls, and integration options.",
          accentColor: "#a78bfa",
          mutedColor: "#a596c9",
        },
        {
          type: "form",
          heading: "Request Your Demo",
          fields: [
            { kind: "text", label: "Full Name", name: "fullName", placeholder: "Jamie Rivera", required: true },
            { kind: "email", label: "Work Email", name: "email", placeholder: "you@company.com", required: true },
            { kind: "select", label: "Team Size", name: "teamSize", required: true, options: ["20-50", "51-200", "201-1000", "1000+"] },
          ],
          submitLabel: "Request Demo",
          accentColor: "#a78bfa",
        },
        {
          type: "iconrow",
          items: [
            { iconName: "Lock", label: "SSO & SCIM ready" },
            { iconName: "ShieldCheck", label: "SOC 2 compliant" },
            { iconName: "Headphones", label: "Dedicated success manager" },
          ],
          accentColor: "#a78bfa",
          textColor: "#ede9fe",
          mutedColor: "#a596c9",
        },
        {
          type: "footer",
          brand: "Lucid AI",
          copyright: "© Lucid AI, Inc.",
          bg: "#0a0716",
          textColor: "#a596c9",
        },
      ],
    },
  ],
};
